/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Log Overview
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../lib/fetcher';
export type AttributeInfoType = typeof AttributeInfoType[keyof typeof AttributeInfoType];


export const AttributeInfoType = {
  numeric: 'numeric',
  categorical: 'categorical',
} as const;

export interface AttributeInfo {
  name: string;
  type: AttributeInfoType;
}

export interface HistogramBody {
  bins?: number | null;
}

export interface HistogramBin {
  start: number;
  end: number;
  count: number;
}

export interface Histogram {
  bins: HistogramBin[];
  missing_count: number;
  total_count: number;
}

export interface CategoricalBody {
  top_k?: number | null;
}

export interface CategoricalEntry {
  value: string;
  count: number;
}

export interface Categorical {
  value_counts: CategoricalEntry[];
  missing_count: number;
  total_count: number;
  truncated: boolean;
}

export interface KdeBody {
  /**
   * @minimum 10
   * @maximum 1000
   */
  n_points?: number;
  /**
   * @minimum 0.1
   * @maximum 5
   */
  bandwidth?: number;
}

export interface KdePoint {
  x: number;
  y: number;
}

export interface Kde {
  points: KdePoint[];
  missing_count: number;
  total_count: number;
}

export interface ViolinBody {
  /**
   * @minimum 10
   * @maximum 1000
   */
  n_points?: number;
}

export interface ViolinStats {
  min: number;
  max: number;
  q1: number;
  median: number;
  q3: number;
}

export interface Violin {
  kde_points: KdePoint[];
  stats: ViolinStats | null;
  missing_count: number;
  total_count: number;
}

export type EventAttributes200 = {[key: string]: AttributeInfo[]};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Event Attributes
 */
export const eventAttributes = (
    ocelId: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<EventAttributes200>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/attributes`, method: 'POST', signal
    },
      options);
    }
  



export const getEventAttributesQueryKey = (ocelId: string,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/attributes`
    ] as const;
    }

    
export const getEventAttributesQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributes>>, TError = unknown>(ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributesQueryKey(ocelId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributes>>> = ({ signal }) => eventAttributes(ocelId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributesQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributes>>>
export type EventAttributesQueryError = unknown


export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = unknown>(
 ocelId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributes>>,
          TError,
          Awaited<ReturnType<typeof eventAttributes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = unknown>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributes>>,
          TError,
          Awaited<ReturnType<typeof eventAttributes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = unknown>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attributes
 */

export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = unknown>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributesQueryOptions(ocelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Event Attribute Histogram
 */
export const eventAttributeHistogram = (
    ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Histogram>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/histogram`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: histogramBody, signal
    },
      options);
    }
  



export const getEventAttributeHistogramQueryKey = (ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody?: HistogramBody,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/histogram`, histogramBody
    ] as const;
    }

    
export const getEventAttributeHistogramQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = void>(ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeHistogramQueryKey(ocelId,eventType,attribute,histogramBody);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeHistogram>>> = ({ signal }) => eventAttributeHistogram(ocelId,eventType,attribute,histogramBody, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && eventType && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeHistogram>>>
export type EventAttributeHistogramQueryError = void


export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeHistogram>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeHistogram>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeHistogram>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeHistogram>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute Histogram
 */

export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeHistogramQueryOptions(ocelId,eventType,attribute,histogramBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Event Attribute Categorical
 */
export const eventAttributeCategorical = (
    ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody: CategoricalBody,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Categorical>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/categorical`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: categoricalBody, signal
    },
      options);
    }
  



export const getEventAttributeCategoricalQueryKey = (ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody?: CategoricalBody,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/categorical`, categoricalBody
    ] as const;
    }

    
export const getEventAttributeCategoricalQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeCategorical>>, TError = void>(ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody: CategoricalBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeCategorical>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeCategoricalQueryKey(ocelId,eventType,attribute,categoricalBody);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeCategorical>>> = ({ signal }) => eventAttributeCategorical(ocelId,eventType,attribute,categoricalBody, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && eventType && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeCategorical>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeCategoricalQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeCategorical>>>
export type EventAttributeCategoricalQueryError = void


export function useEventAttributeCategorical<TData = Awaited<ReturnType<typeof eventAttributeCategorical>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody: CategoricalBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeCategorical>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeCategorical>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeCategorical>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeCategorical<TData = Awaited<ReturnType<typeof eventAttributeCategorical>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody: CategoricalBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeCategorical>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeCategorical>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeCategorical>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeCategorical<TData = Awaited<ReturnType<typeof eventAttributeCategorical>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody: CategoricalBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeCategorical>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute Categorical
 */

export function useEventAttributeCategorical<TData = Awaited<ReturnType<typeof eventAttributeCategorical>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    categoricalBody: CategoricalBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeCategorical>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeCategoricalQueryOptions(ocelId,eventType,attribute,categoricalBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Event Attribute KDE
 */
export const eventAttributeKde = (
    ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody: KdeBody,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Kde>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/kde`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: kdeBody, signal
    },
      options);
    }
  



export const getEventAttributeKdeQueryKey = (ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody?: KdeBody,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/kde`, kdeBody
    ] as const;
    }

    
export const getEventAttributeKdeQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeKde>>, TError = void>(ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody: KdeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeKde>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeKdeQueryKey(ocelId,eventType,attribute,kdeBody);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeKde>>> = ({ signal }) => eventAttributeKde(ocelId,eventType,attribute,kdeBody, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && eventType && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeKde>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeKdeQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeKde>>>
export type EventAttributeKdeQueryError = void


export function useEventAttributeKde<TData = Awaited<ReturnType<typeof eventAttributeKde>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody: KdeBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeKde>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeKde>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeKde>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeKde<TData = Awaited<ReturnType<typeof eventAttributeKde>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody: KdeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeKde>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeKde>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeKde>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeKde<TData = Awaited<ReturnType<typeof eventAttributeKde>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody: KdeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeKde>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute KDE
 */

export function useEventAttributeKde<TData = Awaited<ReturnType<typeof eventAttributeKde>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    kdeBody: KdeBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeKde>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeKdeQueryOptions(ocelId,eventType,attribute,kdeBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Event Attribute Violin
 */
export const eventAttributeViolin = (
    ocelId: string,
    eventType: string,
    attribute: string,
    violinBody: ViolinBody,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Violin>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/violin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: violinBody, signal
    },
      options);
    }
  



export const getEventAttributeViolinQueryKey = (ocelId: string,
    eventType: string,
    attribute: string,
    violinBody?: ViolinBody,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/violin`, violinBody
    ] as const;
    }

    
export const getEventAttributeViolinQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeViolin>>, TError = void>(ocelId: string,
    eventType: string,
    attribute: string,
    violinBody: ViolinBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeViolin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeViolinQueryKey(ocelId,eventType,attribute,violinBody);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeViolin>>> = ({ signal }) => eventAttributeViolin(ocelId,eventType,attribute,violinBody, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && eventType && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeViolin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeViolinQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeViolin>>>
export type EventAttributeViolinQueryError = void


export function useEventAttributeViolin<TData = Awaited<ReturnType<typeof eventAttributeViolin>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    violinBody: ViolinBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeViolin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeViolin>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeViolin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeViolin<TData = Awaited<ReturnType<typeof eventAttributeViolin>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    violinBody: ViolinBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeViolin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeViolin>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeViolin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeViolin<TData = Awaited<ReturnType<typeof eventAttributeViolin>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    violinBody: ViolinBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeViolin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute Violin
 */

export function useEventAttributeViolin<TData = Awaited<ReturnType<typeof eventAttributeViolin>>, TError = void>(
 ocelId: string,
    eventType: string,
    attribute: string,
    violinBody: ViolinBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeViolin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeViolinQueryOptions(ocelId,eventType,attribute,violinBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
