/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Log Overview
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../lib/fetcher';
export type AttributeInfoSchemaType = typeof AttributeInfoSchemaType[keyof typeof AttributeInfoSchemaType];


export const AttributeInfoSchemaType = {
  numeric: 'numeric',
  categorical: 'categorical',
} as const;

export interface AttributeInfoSchema {
  name: string;
  type: AttributeInfoSchemaType;
}

export interface EventInstanceSchema {
  id: string;
  timestamp: string;
  value: number | null;
}

/**
 * Request range. Either endpoint may be omitted for an open range.
 */
export interface RangeInput {
  min?: number | null;
  max?: number | null;
}

export interface EventInstancesBody {
  range?: RangeInput | null;
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
}

export interface EventInstancesSchema {
  instances: EventInstanceSchema[];
  matching_count: number;
  truncated: boolean;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HistogramBinSchema {
  start: number;
  end: number;
  count: number;
}

export interface HistogramBody {
  range?: RangeInput | null;
  bins?: number | null;
}

export interface HistogramCountsSchema {
  covered: number;
  missing: number;
  total: number;
}

export interface RangeSchema {
  min: number;
  max: number;
}

export interface HistogramSchema {
  bins: HistogramBinSchema[];
  domain: RangeSchema | null;
  covered: RangeSchema | null;
  counts: HistogramCountsSchema;
}

export type EventAttributesParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type EventAttributes200 = {[key: string]: AttributeInfoSchema[]};

export type EventAttributeHistogramParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type EventAttributeInstancesParams = {
ocel_version?: 'original' | 'filtered' | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Event Attributes
 */
export const eventAttributes = (
    ocelId: string | null,
    params?: EventAttributesParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<EventAttributes200>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/attributes`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getEventAttributesQueryKey = (ocelId: string | null,
    params?: EventAttributesParams,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/attributes`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getEventAttributesQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributes>>, TError = HTTPValidationError>(ocelId: string | null,
    params?: EventAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributesQueryKey(ocelId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributes>>> = ({ signal }) => eventAttributes(ocelId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributesQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributes>>>
export type EventAttributesQueryError = HTTPValidationError


export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params: undefined |  EventAttributesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributes>>,
          TError,
          Awaited<ReturnType<typeof eventAttributes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params?: EventAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributes>>,
          TError,
          Awaited<ReturnType<typeof eventAttributes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params?: EventAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attributes
 */

export function useEventAttributes<TData = Awaited<ReturnType<typeof eventAttributes>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params?: EventAttributesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributesQueryOptions(ocelId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Event Attribute Histogram
 */
export const eventAttributeHistogram = (
    ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
    params?: EventAttributeHistogramParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<HistogramSchema>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/histogram`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: histogramBody,
        params, signal
    },
      options);
    }
  



export const getEventAttributeHistogramQueryKey = (ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody?: HistogramBody,
    params?: EventAttributeHistogramParams,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/histogram`, ...(params ? [params] : []), histogramBody
    ] as const;
    }

    
export const getEventAttributeHistogramQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = HTTPValidationError>(ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
    params?: EventAttributeHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeHistogramQueryKey(ocelId,eventType,attribute,histogramBody,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeHistogram>>> = ({ signal }) => eventAttributeHistogram(ocelId,eventType,attribute,histogramBody,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && eventType && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeHistogram>>>
export type EventAttributeHistogramQueryError = HTTPValidationError


export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
    params: undefined |  EventAttributeHistogramParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeHistogram>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeHistogram>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
    params?: EventAttributeHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeHistogram>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeHistogram>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
    params?: EventAttributeHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute Histogram
 */

export function useEventAttributeHistogram<TData = Awaited<ReturnType<typeof eventAttributeHistogram>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    histogramBody: HistogramBody,
    params?: EventAttributeHistogramParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeHistogram>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeHistogramQueryOptions(ocelId,eventType,attribute,histogramBody,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Event Attribute Instances
 */
export const eventAttributeInstances = (
    ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody: EventInstancesBody,
    params?: EventAttributeInstancesParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<EventInstancesSchema>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/instances`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventInstancesBody,
        params, signal
    },
      options);
    }
  



export const getEventAttributeInstancesQueryKey = (ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody?: EventInstancesBody,
    params?: EventAttributeInstancesParams,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/${eventType}/${attribute}/instances`, ...(params ? [params] : []), eventInstancesBody
    ] as const;
    }

    
export const getEventAttributeInstancesQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeInstances>>, TError = HTTPValidationError>(ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody: EventInstancesBody,
    params?: EventAttributeInstancesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeInstances>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeInstancesQueryKey(ocelId,eventType,attribute,eventInstancesBody,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeInstances>>> = ({ signal }) => eventAttributeInstances(ocelId,eventType,attribute,eventInstancesBody,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && eventType && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeInstances>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeInstancesQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeInstances>>>
export type EventAttributeInstancesQueryError = HTTPValidationError


export function useEventAttributeInstances<TData = Awaited<ReturnType<typeof eventAttributeInstances>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody: EventInstancesBody,
    params: undefined |  EventAttributeInstancesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeInstances>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeInstances>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeInstances>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeInstances<TData = Awaited<ReturnType<typeof eventAttributeInstances>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody: EventInstancesBody,
    params?: EventAttributeInstancesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeInstances>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeInstances>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeInstances>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeInstances<TData = Awaited<ReturnType<typeof eventAttributeInstances>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody: EventInstancesBody,
    params?: EventAttributeInstancesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeInstances>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute Instances
 */

export function useEventAttributeInstances<TData = Awaited<ReturnType<typeof eventAttributeInstances>>, TError = HTTPValidationError>(
 ocelId: string | null,
    eventType: string,
    attribute: string,
    eventInstancesBody: EventInstancesBody,
    params?: EventAttributeInstancesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeInstances>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeInstancesQueryOptions(ocelId,eventType,attribute,eventInstancesBody,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
