/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Log Overview
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../lib/fetcher';
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface NumericValues {
  values: number[];
  missing_count: number;
}

export type EventAttributeValuesParams = {
activity?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Event Attribute Values
 */
export const eventAttributeValues = (
    ocelId: string | null,
    attribute: string,
    params?: EventAttributeValuesParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<NumericValues>(
      {url: `/api/external/modules/log-overview/v1/${ocelId}/events/attributes/${attribute}/values`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getEventAttributeValuesQueryKey = (ocelId: string | null,
    attribute: string,
    params?: EventAttributeValuesParams,) => {
    return [
    `/api/external/modules/log-overview/v1/${ocelId}/events/attributes/${attribute}/values`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getEventAttributeValuesQueryOptions = <TData = Awaited<ReturnType<typeof eventAttributeValues>>, TError = HTTPValidationError>(ocelId: string | null,
    attribute: string,
    params?: EventAttributeValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventAttributeValuesQueryKey(ocelId,attribute,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventAttributeValues>>> = ({ signal }) => eventAttributeValues(ocelId,attribute,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId && attribute),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventAttributeValues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventAttributeValuesQueryResult = NonNullable<Awaited<ReturnType<typeof eventAttributeValues>>>
export type EventAttributeValuesQueryError = HTTPValidationError


export function useEventAttributeValues<TData = Awaited<ReturnType<typeof eventAttributeValues>>, TError = HTTPValidationError>(
 ocelId: string | null,
    attribute: string,
    params: undefined |  EventAttributeValuesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeValues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeValues>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeValues<TData = Awaited<ReturnType<typeof eventAttributeValues>>, TError = HTTPValidationError>(
 ocelId: string | null,
    attribute: string,
    params?: EventAttributeValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeValues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventAttributeValues>>,
          TError,
          Awaited<ReturnType<typeof eventAttributeValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventAttributeValues<TData = Awaited<ReturnType<typeof eventAttributeValues>>, TError = HTTPValidationError>(
 ocelId: string | null,
    attribute: string,
    params?: EventAttributeValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Event Attribute Values
 */

export function useEventAttributeValues<TData = Awaited<ReturnType<typeof eventAttributeValues>>, TError = HTTPValidationError>(
 ocelId: string | null,
    attribute: string,
    params?: EventAttributeValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventAttributeValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventAttributeValuesQueryOptions(ocelId,attribute,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
