[project]
name = "ocelescope-module-filter"
version = "0.7.0"
description = "Ocelescope backend module providing basic filtering of OCELs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.136.0",
  "ocelescope>=0.7.0,<0.8.0",
  "ocelescope-backend>=0.7.0,<0.8.0",
  "packaging>=24.0",
  "pydantic>=2.11.7",
]

[project.entry-points."ocelescope_backend.modules"]
filterV1 = "ocelescope_module_filter.module:Filter"


[build-system]
requires = ["uv_build>=0.11.20,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.sources]
ocelescope = { workspace = true }
ocelescope-backend = { workspace = true }
