repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        files: .*\.py$
        exclude: ^template/
      - id: end-of-file-fixer
        files: .*\.py$
        exclude: ^template/
      - id: trailing-whitespace
        files: .*\.py$
        exclude: ^template/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7 
    hooks:
      - id: ruff
        types_or: [python, pyi]
        exclude: ^template/
      - id: ruff-format
        types_or: [python, pyi]
        exclude: ^template/
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1" 
    hooks:
      - id: biome-format
        additional_dependencies: ["@biomejs/biome@2.4.2"]
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1" 
    hooks:
      - id: biome-lint
        additional_dependencies: ["@biomejs/biome@2.4.2"]
  - repo: local
    hooks:
      - id: generate-api
        name: Generate Openapi json
        entry: just api
        language: system
        pass_filenames: false
        files: ^src/backend/
