services:
  backend:
    build:
      dockerfile: ./src/backend/dev.Dockerfile
    volumes:
      - ./data:/data
      - plugins_store:/plugins
    environment:
      - DATA_DIR=/data
      - PLUGIN_DIR=/plugins
    develop:
      watch:
        - action: sync+restart
          path: ./src/backend
          target: /app
        - action: sync+restart
          path: ./src/ocelescope
          target: /app
        - action: rebuild
          path: ./uv.lock
  frontend:
    build:
      context: ./src/frontend/
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./src/frontend/
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./src/frontend/package-lock.json

volumes:
  plugins_store:
