services:
  backend:
    build:
      dockerfile: ./src/backend/Dockerfile
      additional_contexts:
        data: ./data
    volumes:
      - plugins_store:/plugins
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend/
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  plugins_store:
