packages:
  - src/frontend/app
  - src/frontend/packages/**/*
  - src/frontend/modules/**/*

allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  sharp: true

catalog:
  "@apidevtools/json-schema-ref-parser": ^15.3.1
  "@dagrejs/dagre": ^3.0.0
  "@faker-js/faker": ^10.4.0
  "@floating-ui/react": ^0.27.18
  "@hpcc-js/wasm-graphviz": ^1.21.0
  "@mantine/carousel": ^9.4.0
  "@mantine/charts": ^9.4.0
  "@mantine/core": ^9.4.0
  "@mantine/dates": ^9.4.0
  "@mantine/dropzone": ^9.4.0
  "@mantine/hooks": ^9.4.0
  "@mantine/notifications": ^9.4.0
  "@marko19907/string-to-color": ^1.0.2
  '@ocelescope/ocelot': ^0.1.2
  '@r4pm/components': ^0.1.1
  "@rjsf/core": ^6.6.2
  "@rjsf/mantine": ^6.6.2
  "@rjsf/utils": ^6.6.2
  "@rjsf/validator-ajv8": ^6.6.2
  "@storybook/react-vite": ^10.3.5
  "@tanstack/react-query": ^5.90.21
  "@tanstack/react-query-devtools": ^5.91.3
  "@tsconfig/strictest": ^2.0.8
  "@tsdown/css": ^0.22.0
  "@types/css-modules": ^1.0.5
  "@types/file-saver": ^2.0.7
  "@types/lodash": ^4.17.23
  "@types/node": ^25.0.3
  '@types/object-hash': ^3.0.6
  "@types/qs": ^6.15.1
  "@types/react": ^19.2.7
  "@types/react-cytoscapejs": ^1.2.6
  "@types/react-dom": ^19.2.3
  "@xyflow/react": ^12.10.1
  axios: ^1.18.0
  bumpp: ^11.0.0
  clsx: ^2.1.1
  content-disposition-attachment: ^0.3.1
  cspell: ^10.0.1
  cytoscape: ^3.33.1
  dayjs: ^1.11.19
  echarts: ^5.6.0
  echarts-for-react: ^3.0.6
  elkjs: ^0.11.0
  embla-carousel: ^8.6.0
  embla-carousel-react: ^8.6.0
  file-saver: ^2.0.5
  flat: ^6.0.1
  html-to-image: 1.11.13
  json-schema-traverse: ^1.0.0
  jspdf: ^4.2.1
  lodash: ^4.17.23
  lucide-react: ^1.0.0
  mantine-datatable: ^9.3.1
  next: ^16.1.6
  object-hash: ^3.0.0
  orval: ^8.5.2
  qs: ^6.15.1
  react: ^19.2.0
  react-cytoscapejs: ^2.0.0
  react-dom: ^19.2.0
  react-hook-form: ^7.71.2
  react-plotly.js: ^4.0.0
  react-zoom-pan-pinch: ^4.0.0
  recharts: ^3.2.1
  storybook: ^10.3.5
  tsdown: ^0.22.0
  typescript: ^5.9.3
  uniqolor: ^1.1.1
  zod: ^4.3.6
  zustand: ^5.0.11

catalogMode: prefer

ignoredBuiltDependencies:
  - core-js
  - es5-ext
  - esbuild
  - sharp

minimumReleaseAgeExclude:
  - '@mantine/carousel@9.4.0'
  - '@mantine/charts@9.4.0'
  - '@mantine/core@9.4.0'
  - '@mantine/dates@9.4.0'
  - '@mantine/dropzone@9.4.0'
  - '@mantine/hooks@9.4.0'
  - '@mantine/notifications@9.4.0'
  - '@mantine/store@9.4.0'
  - '@ocelescope/ocelot@0.1.2'
