QEL_ITEM_TYPE = "qel:item_type"
QEL_QUANTITY = "qel:quantity"
QEL_QUANTITY_UPDATE = "qel:quantity_update"
QEL_ILVL = "qel:itlvl"

XML_QUANTITY_EXTENSION = "quantity-extension"
XML_OPERATIONS = "operations"
XML_OPERATION = "operation"
XML_QUANTITIES = "quantities"
XML_QUANTITY = "quantity"
XML_EVENT_ID = "event-id"
XML_OBJECT_ID = "object-id"
XML_ITEM = "item"
XML_ITEM_TYPE = "type"
XML_QUANTITY_TYPE = "type"

JSON_QUANTITY_EXTENSION = "quantityExtension"
JSON_OPERATIONS = "operations"
JSON_OPERATION = "operation"
JSON_QUANTITIES = "quantities"
JSON_QUANTITY = "quantity"
JSON_EVENT_ID = "eventId"
JSON_OBJECT_ID = "objectId"
JSON_ITEM = "item"
JSON_ITEM_TYPE = "type"
JSON_QUANTITY_TYPE = "type"
