packages:
  - app
  - packages/**/*
  - modules/*

catalog:
  '@dagrejs/dagre': ^2.0.4
  '@mantine/core': ^8.3.14
  '@mantine/dropzone': ^8.3.14
  '@mantine/hooks': ^8.3.14
  '@marko19907/string-to-color': ^1.0.2
  '@tanstack/react-query': ^5.90.21
  '@types/file-saver': ^2.0.7
  '@xyflow/react': ^12.10.1
  clsx: ^2.1.1
  content-disposition-attachment: ^0.3.1
  dayjs: ^1.11.19
  elkjs: ^0.11.0
  file-saver: ^2.0.5
  html-to-image: ^1.11.13
  lucide-react: ^0.563.0
  mantine-datatable: ^8.3.13
  next: ^16.1.6
  react: ^19.2.0
  react-dom: ^19.2.0
  zod: ^4.3.6
  zustand: ^5.0.11

catalogMode: prefer
