[project]
name = "ocelescope"
version = "0.7.0"
description = "General tools for working with Object-Centric Event Logs and building Ocelescope plugins"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Typing :: Typed",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Information Analysis",
]

dependencies = [
  "duckdb>=1.5.4",
  "graphviz>=0.21",
  "ijson>=3.5.0",
  "lxml>=6.1.1",
  "matplotlib>=3.10.9",
  "orjson>=3.11.7",
  "pandas>=2.3.1",
  "plotly>=6.3.1",
  "pm4py~=2.7.23",
  "polars>=1.40.1",
  "pyarrow>=24.0.0",
  "pydantic>=2.11.7",
  "r4pm[polars]>=0.6.0",
]

[project.urls]
Homepage = "https://www.ocelescope.org"
Documentation = "https://www.ocelescope.org"
Repository = "https://github.com/promi4s/ocelescope"
Issues = "https://github.com/promi4s/ocelescope/issues"

[project.scripts]
ocelescope = "ocelescope.tools.cli:main"

[tool.uv]
package = true

[project.optional-dependencies]
plugin = [
  "more-itertools>=11.1.0",
  "networkx>=3.5",
  "pulp>=3.3.2",
  "numpy>=2.3.2",
  "scikit-learn>=1.9.0",
]

[build-system]
requires = ["uv_build>=0.11.20,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["pyarrow-stubs>=20.0.0.20260625"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
fix = true
lint.ignore = ["E731", "E501"]
