# Modifications to the SwaggerUI interface generated by FastAPI

# Hide curl commands
# source: https://github.com/tiangolo/fastapi/discussions/3853#discussioncomment-1388209

from typing import Literal

from fastapi import FastAPI
from api.config import config
from starlette.responses import HTMLResponse


def get_rapidoc_html(
    *,
    openapi_url: str,
    title: str,
    rapidoc_js_url: str = "https://unpkg.com/rapidoc/dist/rapidoc-min.js",
    rapidoc_favicon_url: str = "https://rapidocweb.com/images/logo.png",
):
    return HTMLResponse(
        f"""
    <!doctype html> <!-- Important: must specify -->
    <html>
        <head>
            <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 characters -->
            <script type="module" src="{rapidoc_js_url}"></script>
            <title>{title}</title>
            <link rel="shortcut icon" href="{rapidoc_favicon_url}">
        </head>
        <body>
            <rapi-doc
                spec-url="{openapi_url}"
                layout="row"
                render-style="view"
                allow-server-selection="false"
                show-header="false"
                show-components="true"
                api-key-name="{config.SESSION_ID_HEADER}"
                api-key-location="header"
                api-key-value="-"
            ></rapi-doc>
        </body>
    </html>
    """
    )


def init_custom_docs(app: FastAPI):
    assert app.openapi_url is not None

    # app.mount("/static", StaticFiles(directory="static"), name="static")

    @app.get("/docs", include_in_schema=False)
    async def docs(ui: Literal["swaggerui", "rapidoc"] = "rapidoc", curl: bool = True):
        if ui == "rapidoc":
            return get_rapidoc_html(
                openapi_url=app.openapi_url or "/",
                title=app.title + " - rapidoc",
            )
