/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Exploration
 * OpenAPI spec version: 1.0
 */
/**
 * Objects of a type by how often they executed each activity, in bands.
 */
export interface ActivityExecutionFrequency {
  analysis: 'activity-execution-frequency';
  object_type: string;
}

export interface Bins {
  kind: 'bins';
  count?: number | null;
}

export interface Categories {
  kind: 'categories';
  /**
     * @minimum 1
     * @maximum 500
     */
  limit?: number;
}

/**
 * An event attribute's values, one per event of an activity.
 */
export interface EventAttributeDistribution {
  analysis: 'event-attribute-distribution';
  activity: string;
  attribute: string;
  grouping: Categories | Bins;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * Exact execution counts per object, for activities some object repeats.
 */
export interface ObjectActivityExecutionDistribution {
  analysis: 'object-activity-execution-distribution';
  object_type: string;
}

/**
 * An object attribute's value at each event of an activity, one per
 * event-object pair. A change at the event's own timestamp already applies.
 */
export interface ObjectAttributeDistribution {
  analysis: 'object-attribute-distribution';
  activity: string;
  object_type: string;
  attribute: string;
  grouping: Categories | Bins;
}

/**
 * Every attribute change of an object and every event it takes part in,
 * in time order, each with the attribute values in effect at that point.
 */
export interface ObjectAttributeTimeline {
  analysis: 'object-attribute-timeline';
  object_id: string;
  attributes?: string[] | null;
}

/**
 * Events by how many distinct objects of each type they involve.
 */
export interface ObjectCountsPerEvent {
  analysis: 'object-counts-per-event';
  activities?: string[];
}

/**
 * Distinct objects of a type per event of an activity, including zero.
 */
export interface ObjectInvolvementDistribution {
  analysis: 'object-involvement-distribution';
  activity: string;
  object_type: string;
  grouping: Categories | Bins;
}

/**
 * The most frequent exact sets of object types per event, by activity.
 */
export interface ObjectTypeCombinations {
  analysis: 'object-type-combinations';
  /**
     * @minimum 1
     * @maximum 50
     */
  limit?: number;
  activities?: string[];
}

export type ResultRowsItem = { [key: string]: unknown };

export type ResultMeta = { [key: string]: unknown };

/**
 * What every analysis returns: tidy rows, plus named population figures.
 */
export interface Result {
  rows: ResultRowsItem[];
  meta?: ResultMeta;
}

export type TimeBetweenActivitiesUnit = typeof TimeBetweenActivitiesUnit[keyof typeof TimeBetweenActivitiesUnit];


export const TimeBetweenActivitiesUnit = {
  seconds: 'seconds',
  minutes: 'minutes',
  hours: 'hours',
  days: 'days',
} as const;

/**
 * Durations from a source to a directly following target activity, once
 * each object's trace is reduced to just those two activities.
 */
export interface TimeBetweenActivities {
  analysis: 'time-between-activities';
  source_activity: string;
  target_activity: string;
  object_type: string;
  unit: TimeBetweenActivitiesUnit;
  bin_count?: number | null;
}

/**
 * Events by how many distinct objects they involve, per activity.
 * Events without any object count as involving zero.
 */
export const TotalObjectInvolvementValue = {
  analysis: 'total-object-involvement',
} as const;
export type TotalObjectInvolvement = typeof TotalObjectInvolvementValue;


