/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Querying
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../lib/fetcher';
export interface ActivityEventCount {
  activity: string;
  event_count: number;
}

export interface ActivityExecutionFrequencyQuery {
  object_type: string;
}

export interface ActivityExecutionFrequencyRow {
  activity: string;
  lower_bound: number;
  upper_bound: number | null;
  label: string;
  object_count: number;
}

export interface ActivityExecutionFrequencyResponse {
  rows: ActivityExecutionFrequencyRow[];
  object_activity_pair_count: number;
  object_count: number;
  maximum_execution_count: number;
}

export interface ActivityObjectTypePair {
  activity: string;
  object_type: string;
}

export type AttributeSchemaItemPhysicalType = typeof AttributeSchemaItemPhysicalType[keyof typeof AttributeSchemaItemPhysicalType];


export const AttributeSchemaItemPhysicalType = {
  number: 'number',
  string: 'string',
  boolean: 'boolean',
  datetime: 'datetime',
  unknown: 'unknown',
} as const;

export type AttributeSchemaItemInferredAnalyticalType = typeof AttributeSchemaItemInferredAnalyticalType[keyof typeof AttributeSchemaItemInferredAnalyticalType];


export const AttributeSchemaItemInferredAnalyticalType = {
  categorical: 'categorical',
  discrete: 'discrete',
  continuous: 'continuous',
  temporal: 'temporal',
  unknown: 'unknown',
} as const;

export type AttributeSchemaItemAnalyticalType = typeof AttributeSchemaItemAnalyticalType[keyof typeof AttributeSchemaItemAnalyticalType];


export const AttributeSchemaItemAnalyticalType = {
  categorical: 'categorical',
  discrete: 'discrete',
  continuous: 'continuous',
  temporal: 'temporal',
  unknown: 'unknown',
} as const;

export interface AttributeSchemaItem {
  name: string;
  physical_type: AttributeSchemaItemPhysicalType;
  inferred_analytical_type: AttributeSchemaItemInferredAnalyticalType;
  analytical_type: AttributeSchemaItemAnalyticalType;
  present_count: number;
  missing_count: number;
  distinct_count: number;
}

export interface ActivitySchemaItem {
  name: string;
  event_count: number;
  attributes: AttributeSchemaItem[];
}

export type ObjectAttributeSchemaItemPhysicalType = typeof ObjectAttributeSchemaItemPhysicalType[keyof typeof ObjectAttributeSchemaItemPhysicalType];


export const ObjectAttributeSchemaItemPhysicalType = {
  number: 'number',
  string: 'string',
  boolean: 'boolean',
  datetime: 'datetime',
  unknown: 'unknown',
} as const;

export type ObjectAttributeSchemaItemInferredAnalyticalType = typeof ObjectAttributeSchemaItemInferredAnalyticalType[keyof typeof ObjectAttributeSchemaItemInferredAnalyticalType];


export const ObjectAttributeSchemaItemInferredAnalyticalType = {
  categorical: 'categorical',
  discrete: 'discrete',
  continuous: 'continuous',
  temporal: 'temporal',
  unknown: 'unknown',
} as const;

export type ObjectAttributeSchemaItemAnalyticalType = typeof ObjectAttributeSchemaItemAnalyticalType[keyof typeof ObjectAttributeSchemaItemAnalyticalType];


export const ObjectAttributeSchemaItemAnalyticalType = {
  categorical: 'categorical',
  discrete: 'discrete',
  continuous: 'continuous',
  temporal: 'temporal',
  unknown: 'unknown',
} as const;

export type ObjectAttributeSchemaItemBehavior = typeof ObjectAttributeSchemaItemBehavior[keyof typeof ObjectAttributeSchemaItemBehavior];


export const ObjectAttributeSchemaItemBehavior = {
  static: 'static',
  dynamic: 'dynamic',
} as const;

export interface ObjectAttributeSchemaItem {
  name: string;
  physical_type: ObjectAttributeSchemaItemPhysicalType;
  inferred_analytical_type: ObjectAttributeSchemaItemInferredAnalyticalType;
  analytical_type: ObjectAttributeSchemaItemAnalyticalType;
  present_count: number;
  missing_count: number;
  distinct_count: number;
  behavior: ObjectAttributeSchemaItemBehavior;
  initial_present_count: number;
  current_present_count: number;
  observed_value_count: number;
  change_count: number;
  changed_object_count: number;
}

export interface ObjectTypeSchemaItem {
  name: string;
  object_count: number;
  attributes: ObjectAttributeSchemaItem[];
}

export interface AnalyticalSchemaResponse {
  schema_version?: '1';
  activities: ActivitySchemaItem[];
  object_types: ObjectTypeSchemaItem[];
}

export type AttributeClassificationOverrideScope = typeof AttributeClassificationOverrideScope[keyof typeof AttributeClassificationOverrideScope];


export const AttributeClassificationOverrideScope = {
  event: 'event',
  object: 'object',
} as const;

export type AttributeClassificationOverrideAnalyticalType = typeof AttributeClassificationOverrideAnalyticalType[keyof typeof AttributeClassificationOverrideAnalyticalType];


export const AttributeClassificationOverrideAnalyticalType = {
  categorical: 'categorical',
  discrete: 'discrete',
  continuous: 'continuous',
  temporal: 'temporal',
  unknown: 'unknown',
} as const;

export interface AttributeClassificationOverride {
  scope: AttributeClassificationOverrideScope;
  entity_type: string;
  attribute: string;
  analytical_type: AttributeClassificationOverrideAnalyticalType;
}

export interface CategoryGrouping {
  kind: 'categories';
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
}

export type DistributionBucketKind = typeof DistributionBucketKind[keyof typeof DistributionBucketKind];


export const DistributionBucketKind = {
  value: 'value',
  range: 'range',
  missing: 'missing',
  other: 'other',
} as const;

export interface DistributionBucket {
  key: string;
  label: string;
  count: number;
  kind: DistributionBucketKind;
  value?: string | number | boolean | null;
  lower?: number | null;
  upper?: number | null;
  inclusive_upper?: boolean;
}

export interface QueryCounts {
  total: number;
  present: number;
  missing: number;
  represented: number;
}

export interface DistributionResponse {
  buckets: DistributionBucket[];
  counts: QueryCounts;
  truncated: boolean;
}

export interface NumericBinGrouping {
  kind: 'bins';
  count?: number | null;
}

export interface EventAttributeDistributionQuery {
  activity: string;
  attribute: string;
  grouping: CategoryGrouping | NumericBinGrouping;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ObjectAttributeDistributionOptionsResponse {
  pairs: ActivityObjectTypePair[];
}

export interface ObjectAttributeDistributionQuery {
  activity: string;
  object_type: string;
  attribute: string;
  grouping: CategoryGrouping | NumericBinGrouping;
}

export interface ObjectCountPerEventRow {
  activity: string;
  object_type: string;
  object_count: number;
  event_count: number;
}

export interface ObjectCountsPerEventQuery {
  activities?: string[];
}

export interface ObjectCountsPerEventResponse {
  rows: ObjectCountPerEventRow[];
  activity_event_counts: ActivityEventCount[];
}

export interface ObjectInvolvementDistributionQuery {
  activity: string;
  object_type: string;
  grouping: CategoryGrouping | NumericBinGrouping;
}

export interface ObjectInvolvementOption {
  activity: string;
  object_type: string;
  minimum: number;
  maximum: number;
}

export interface ObjectInvolvementOptionsResponse {
  pairs: ObjectInvolvementOption[];
}

export interface ObjectTypeCombinationRow {
  object_types: string[];
  activity: string;
  event_count: number;
}

export interface ObjectTypeCombinationsQuery {
  /**
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
  activities?: string[];
}

export interface ObjectTypeCombinationsResponse {
  rows: ObjectTypeCombinationRow[];
  total_event_count: number;
  represented_event_count: number;
  total_combination_count: number;
  truncated: boolean;
}

export interface UpdateAnalyticalSchemaRequest {
  overrides: AttributeClassificationOverride[];
}

export type QueryEventAttributeDistributionParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type QueryObjectAttributeDistributionParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type QueryObjectCountsPerEventParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type QueryObjectTypeCombinationsParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type QueryActivityExecutionFrequencyParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type QueryObjectInvolvementDistributionParams = {
ocel_version?: 'original' | 'filtered' | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Analytical Schema
 */
export const getAnalyticalSchema = (
    ocelId: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<AnalyticalSchemaResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/analytical-schema`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAnalyticalSchemaQueryKey = (ocelId: string,) => {
    return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/analytical-schema`
    ] as const;
    }

    
export const getGetAnalyticalSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticalSchema>>, TError = HTTPValidationError>(ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticalSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticalSchemaQueryKey(ocelId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticalSchema>>> = ({ signal }) => getAnalyticalSchema(ocelId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticalSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticalSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticalSchema>>>
export type GetAnalyticalSchemaQueryError = HTTPValidationError


export function useGetAnalyticalSchema<TData = Awaited<ReturnType<typeof getAnalyticalSchema>>, TError = HTTPValidationError>(
 ocelId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticalSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticalSchema>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticalSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticalSchema<TData = Awaited<ReturnType<typeof getAnalyticalSchema>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticalSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticalSchema>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticalSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticalSchema<TData = Awaited<ReturnType<typeof getAnalyticalSchema>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticalSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Analytical Schema
 */

export function useGetAnalyticalSchema<TData = Awaited<ReturnType<typeof getAnalyticalSchema>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticalSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticalSchemaQueryOptions(ocelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Update Analytical Schema
 */
export const updateAnalyticalSchema = (
    ocelId: string,
    updateAnalyticalSchemaRequest: UpdateAnalyticalSchemaRequest,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<AnalyticalSchemaResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/analytical-schema`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateAnalyticalSchemaRequest, signal
    },
      options);
    }
  


export const getUpdateAnalyticalSchemaMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAnalyticalSchema>>, TError,{ocelId: string;data: UpdateAnalyticalSchemaRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAnalyticalSchema>>, TError,{ocelId: string;data: UpdateAnalyticalSchemaRequest}, TContext> => {

const mutationKey = ['updateAnalyticalSchema'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAnalyticalSchema>>, {ocelId: string;data: UpdateAnalyticalSchemaRequest}> = (props) => {
          const {ocelId,data} = props ?? {};

          return  updateAnalyticalSchema(ocelId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAnalyticalSchemaMutationResult = NonNullable<Awaited<ReturnType<typeof updateAnalyticalSchema>>>
    export type UpdateAnalyticalSchemaMutationBody = UpdateAnalyticalSchemaRequest
    export type UpdateAnalyticalSchemaMutationError = HTTPValidationError

    /**
 * @summary Update Analytical Schema
 */
export const useUpdateAnalyticalSchema = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAnalyticalSchema>>, TError,{ocelId: string;data: UpdateAnalyticalSchemaRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAnalyticalSchema>>,
        TError,
        {ocelId: string;data: UpdateAnalyticalSchemaRequest},
        TContext
      > => {
      return useMutation(getUpdateAnalyticalSchemaMutationOptions(options), queryClient);
    }
    
/**
 * @summary Query Event Attribute Distribution
 */
export const queryEventAttributeDistribution = (
    ocelId: string | null,
    eventAttributeDistributionQuery: EventAttributeDistributionQuery,
    params?: QueryEventAttributeDistributionParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<DistributionResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/event-attribute-distribution`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: eventAttributeDistributionQuery,
        params, signal
    },
      options);
    }
  


export const getQueryEventAttributeDistributionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryEventAttributeDistribution>>, TError,{ocelId: string | null;data: EventAttributeDistributionQuery;params?: QueryEventAttributeDistributionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryEventAttributeDistribution>>, TError,{ocelId: string | null;data: EventAttributeDistributionQuery;params?: QueryEventAttributeDistributionParams}, TContext> => {

const mutationKey = ['queryEventAttributeDistribution'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryEventAttributeDistribution>>, {ocelId: string | null;data: EventAttributeDistributionQuery;params?: QueryEventAttributeDistributionParams}> = (props) => {
          const {ocelId,data,params} = props ?? {};

          return  queryEventAttributeDistribution(ocelId,data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type QueryEventAttributeDistributionMutationResult = NonNullable<Awaited<ReturnType<typeof queryEventAttributeDistribution>>>
    export type QueryEventAttributeDistributionMutationBody = EventAttributeDistributionQuery
    export type QueryEventAttributeDistributionMutationError = HTTPValidationError

    /**
 * @summary Query Event Attribute Distribution
 */
export const useQueryEventAttributeDistribution = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryEventAttributeDistribution>>, TError,{ocelId: string | null;data: EventAttributeDistributionQuery;params?: QueryEventAttributeDistributionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
        TError,
        {ocelId: string | null;data: EventAttributeDistributionQuery;params?: QueryEventAttributeDistributionParams},
        TContext
      > => {
      return useMutation(getQueryEventAttributeDistributionMutationOptions(options), queryClient);
    }
    
/**
 * @summary Object Attribute Distribution Options
 */
export const getObjectAttributeDistributionOptions = (
    ocelId: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<ObjectAttributeDistributionOptionsResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution/options`, method: 'GET', signal
    },
      options);
    }
  



export const getGetObjectAttributeDistributionOptionsQueryKey = (ocelId: string,) => {
    return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution/options`
    ] as const;
    }

    
export const getGetObjectAttributeDistributionOptionsQueryOptions = <TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError = HTTPValidationError>(ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetObjectAttributeDistributionOptionsQueryKey(ocelId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>> = ({ signal }) => getObjectAttributeDistributionOptions(ocelId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetObjectAttributeDistributionOptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>>
export type GetObjectAttributeDistributionOptionsQueryError = HTTPValidationError


export function useGetObjectAttributeDistributionOptions<TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError = HTTPValidationError>(
 ocelId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetObjectAttributeDistributionOptions<TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetObjectAttributeDistributionOptions<TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Object Attribute Distribution Options
 */

export function useGetObjectAttributeDistributionOptions<TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetObjectAttributeDistributionOptionsQueryOptions(ocelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Query Object Attribute Distribution
 */
export const queryObjectAttributeDistribution = (
    ocelId: string | null,
    objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
    params?: QueryObjectAttributeDistributionParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<DistributionResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: objectAttributeDistributionQuery,
        params, signal
    },
      options);
    }
  


export const getQueryObjectAttributeDistributionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectAttributeDistribution>>, TError,{ocelId: string | null;data: ObjectAttributeDistributionQuery;params?: QueryObjectAttributeDistributionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryObjectAttributeDistribution>>, TError,{ocelId: string | null;data: ObjectAttributeDistributionQuery;params?: QueryObjectAttributeDistributionParams}, TContext> => {

const mutationKey = ['queryObjectAttributeDistribution'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryObjectAttributeDistribution>>, {ocelId: string | null;data: ObjectAttributeDistributionQuery;params?: QueryObjectAttributeDistributionParams}> = (props) => {
          const {ocelId,data,params} = props ?? {};

          return  queryObjectAttributeDistribution(ocelId,data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type QueryObjectAttributeDistributionMutationResult = NonNullable<Awaited<ReturnType<typeof queryObjectAttributeDistribution>>>
    export type QueryObjectAttributeDistributionMutationBody = ObjectAttributeDistributionQuery
    export type QueryObjectAttributeDistributionMutationError = HTTPValidationError

    /**
 * @summary Query Object Attribute Distribution
 */
export const useQueryObjectAttributeDistribution = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectAttributeDistribution>>, TError,{ocelId: string | null;data: ObjectAttributeDistributionQuery;params?: QueryObjectAttributeDistributionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
        TError,
        {ocelId: string | null;data: ObjectAttributeDistributionQuery;params?: QueryObjectAttributeDistributionParams},
        TContext
      > => {
      return useMutation(getQueryObjectAttributeDistributionMutationOptions(options), queryClient);
    }
    
/**
 * @summary Query Object Counts Per Event
 */
export const queryObjectCountsPerEvent = (
    ocelId: string | null,
    objectCountsPerEventQuery: ObjectCountsPerEventQuery,
    params?: QueryObjectCountsPerEventParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<ObjectCountsPerEventResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-counts-per-event`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: objectCountsPerEventQuery,
        params, signal
    },
      options);
    }
  


export const getQueryObjectCountsPerEventMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectCountsPerEvent>>, TError,{ocelId: string | null;data: ObjectCountsPerEventQuery;params?: QueryObjectCountsPerEventParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryObjectCountsPerEvent>>, TError,{ocelId: string | null;data: ObjectCountsPerEventQuery;params?: QueryObjectCountsPerEventParams}, TContext> => {

const mutationKey = ['queryObjectCountsPerEvent'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryObjectCountsPerEvent>>, {ocelId: string | null;data: ObjectCountsPerEventQuery;params?: QueryObjectCountsPerEventParams}> = (props) => {
          const {ocelId,data,params} = props ?? {};

          return  queryObjectCountsPerEvent(ocelId,data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type QueryObjectCountsPerEventMutationResult = NonNullable<Awaited<ReturnType<typeof queryObjectCountsPerEvent>>>
    export type QueryObjectCountsPerEventMutationBody = ObjectCountsPerEventQuery
    export type QueryObjectCountsPerEventMutationError = HTTPValidationError

    /**
 * @summary Query Object Counts Per Event
 */
export const useQueryObjectCountsPerEvent = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectCountsPerEvent>>, TError,{ocelId: string | null;data: ObjectCountsPerEventQuery;params?: QueryObjectCountsPerEventParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
        TError,
        {ocelId: string | null;data: ObjectCountsPerEventQuery;params?: QueryObjectCountsPerEventParams},
        TContext
      > => {
      return useMutation(getQueryObjectCountsPerEventMutationOptions(options), queryClient);
    }
    
/**
 * @summary Query Object Type Combinations
 */
export const queryObjectTypeCombinations = (
    ocelId: string | null,
    objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
    params?: QueryObjectTypeCombinationsParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<ObjectTypeCombinationsResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-type-combinations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: objectTypeCombinationsQuery,
        params, signal
    },
      options);
    }
  


export const getQueryObjectTypeCombinationsMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectTypeCombinations>>, TError,{ocelId: string | null;data: ObjectTypeCombinationsQuery;params?: QueryObjectTypeCombinationsParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryObjectTypeCombinations>>, TError,{ocelId: string | null;data: ObjectTypeCombinationsQuery;params?: QueryObjectTypeCombinationsParams}, TContext> => {

const mutationKey = ['queryObjectTypeCombinations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryObjectTypeCombinations>>, {ocelId: string | null;data: ObjectTypeCombinationsQuery;params?: QueryObjectTypeCombinationsParams}> = (props) => {
          const {ocelId,data,params} = props ?? {};

          return  queryObjectTypeCombinations(ocelId,data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type QueryObjectTypeCombinationsMutationResult = NonNullable<Awaited<ReturnType<typeof queryObjectTypeCombinations>>>
    export type QueryObjectTypeCombinationsMutationBody = ObjectTypeCombinationsQuery
    export type QueryObjectTypeCombinationsMutationError = HTTPValidationError

    /**
 * @summary Query Object Type Combinations
 */
export const useQueryObjectTypeCombinations = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectTypeCombinations>>, TError,{ocelId: string | null;data: ObjectTypeCombinationsQuery;params?: QueryObjectTypeCombinationsParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
        TError,
        {ocelId: string | null;data: ObjectTypeCombinationsQuery;params?: QueryObjectTypeCombinationsParams},
        TContext
      > => {
      return useMutation(getQueryObjectTypeCombinationsMutationOptions(options), queryClient);
    }
    
/**
 * @summary Query Activity Execution Frequency
 */
export const queryActivityExecutionFrequency = (
    ocelId: string | null,
    activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
    params?: QueryActivityExecutionFrequencyParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<ActivityExecutionFrequencyResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/activity-execution-frequency`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: activityExecutionFrequencyQuery,
        params, signal
    },
      options);
    }
  


export const getQueryActivityExecutionFrequencyMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryActivityExecutionFrequency>>, TError,{ocelId: string | null;data: ActivityExecutionFrequencyQuery;params?: QueryActivityExecutionFrequencyParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryActivityExecutionFrequency>>, TError,{ocelId: string | null;data: ActivityExecutionFrequencyQuery;params?: QueryActivityExecutionFrequencyParams}, TContext> => {

const mutationKey = ['queryActivityExecutionFrequency'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryActivityExecutionFrequency>>, {ocelId: string | null;data: ActivityExecutionFrequencyQuery;params?: QueryActivityExecutionFrequencyParams}> = (props) => {
          const {ocelId,data,params} = props ?? {};

          return  queryActivityExecutionFrequency(ocelId,data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type QueryActivityExecutionFrequencyMutationResult = NonNullable<Awaited<ReturnType<typeof queryActivityExecutionFrequency>>>
    export type QueryActivityExecutionFrequencyMutationBody = ActivityExecutionFrequencyQuery
    export type QueryActivityExecutionFrequencyMutationError = HTTPValidationError

    /**
 * @summary Query Activity Execution Frequency
 */
export const useQueryActivityExecutionFrequency = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryActivityExecutionFrequency>>, TError,{ocelId: string | null;data: ActivityExecutionFrequencyQuery;params?: QueryActivityExecutionFrequencyParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
        TError,
        {ocelId: string | null;data: ActivityExecutionFrequencyQuery;params?: QueryActivityExecutionFrequencyParams},
        TContext
      > => {
      return useMutation(getQueryActivityExecutionFrequencyMutationOptions(options), queryClient);
    }
    
/**
 * @summary Object Involvement Options
 */
export const getObjectInvolvementOptions = (
    ocelId: string,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<ObjectInvolvementOptionsResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution/options`, method: 'GET', signal
    },
      options);
    }
  



export const getGetObjectInvolvementOptionsQueryKey = (ocelId: string,) => {
    return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution/options`
    ] as const;
    }

    
export const getGetObjectInvolvementOptionsQueryOptions = <TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError = HTTPValidationError>(ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetObjectInvolvementOptionsQueryKey(ocelId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getObjectInvolvementOptions>>> = ({ signal }) => getObjectInvolvementOptions(ocelId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetObjectInvolvementOptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getObjectInvolvementOptions>>>
export type GetObjectInvolvementOptionsQueryError = HTTPValidationError


export function useGetObjectInvolvementOptions<TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError = HTTPValidationError>(
 ocelId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetObjectInvolvementOptions<TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetObjectInvolvementOptions<TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Object Involvement Options
 */

export function useGetObjectInvolvementOptions<TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError = HTTPValidationError>(
 ocelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getObjectInvolvementOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetObjectInvolvementOptionsQueryOptions(ocelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Query Object Involvement Distribution
 */
export const queryObjectInvolvementDistribution = (
    ocelId: string | null,
    objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
    params?: QueryObjectInvolvementDistributionParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<DistributionResponse>(
      {url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: objectInvolvementDistributionQuery,
        params, signal
    },
      options);
    }
  


export const getQueryObjectInvolvementDistributionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>, TError,{ocelId: string | null;data: ObjectInvolvementDistributionQuery;params?: QueryObjectInvolvementDistributionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>, TError,{ocelId: string | null;data: ObjectInvolvementDistributionQuery;params?: QueryObjectInvolvementDistributionParams}, TContext> => {

const mutationKey = ['queryObjectInvolvementDistribution'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>, {ocelId: string | null;data: ObjectInvolvementDistributionQuery;params?: QueryObjectInvolvementDistributionParams}> = (props) => {
          const {ocelId,data,params} = props ?? {};

          return  queryObjectInvolvementDistribution(ocelId,data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type QueryObjectInvolvementDistributionMutationResult = NonNullable<Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>>
    export type QueryObjectInvolvementDistributionMutationBody = ObjectInvolvementDistributionQuery
    export type QueryObjectInvolvementDistributionMutationError = HTTPValidationError

    /**
 * @summary Query Object Involvement Distribution
 */
export const useQueryObjectInvolvementDistribution = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>, TError,{ocelId: string | null;data: ObjectInvolvementDistributionQuery;params?: QueryObjectInvolvementDistributionParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
        TError,
        {ocelId: string | null;data: ObjectInvolvementDistributionQuery;params?: QueryObjectInvolvementDistributionParams},
        TContext
      > => {
      return useMutation(getQueryObjectInvolvementDistributionMutationOptions(options), queryClient);
    }
