/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Querying
 * OpenAPI spec version: 1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import { customFetch } from "../lib/fetcher";
export interface ActivityEventCount {
  activity: string;
  event_count: number;
}

export interface ActivityExecutionFrequencyQuery {
  object_type: string;
}

export interface ActivityExecutionFrequencyRow {
  activity: string;
  lower_bound: number;
  upper_bound: number | null;
  label: string;
  object_count: number;
}

export interface ActivityExecutionFrequencyResponse {
  rows: ActivityExecutionFrequencyRow[];
  object_activity_pair_count: number;
  object_count: number;
  maximum_execution_count: number;
}

export interface ActivityObjectTypePair {
  activity: string;
  object_type: string;
}

export type AttributeSchemaItemPhysicalType =
  (typeof AttributeSchemaItemPhysicalType)[keyof typeof AttributeSchemaItemPhysicalType];

export const AttributeSchemaItemPhysicalType = {
  number: "number",
  string: "string",
  boolean: "boolean",
  datetime: "datetime",
  unknown: "unknown",
} as const;

export type AttributeSchemaItemAnalyticalType =
  (typeof AttributeSchemaItemAnalyticalType)[keyof typeof AttributeSchemaItemAnalyticalType];

export const AttributeSchemaItemAnalyticalType = {
  categorical: "categorical",
  discrete: "discrete",
  continuous: "continuous",
  temporal: "temporal",
  unknown: "unknown",
} as const;

export interface AttributeSchemaItem {
  name: string;
  physical_type: AttributeSchemaItemPhysicalType;
  analytical_type: AttributeSchemaItemAnalyticalType;
  present_count: number;
  missing_count: number;
  distinct_count: number;
}

export interface ActivitySchemaItem {
  name: string;
  event_count: number;
  attributes: AttributeSchemaItem[];
}

export type ObjectAttributeSchemaItemPhysicalType =
  (typeof ObjectAttributeSchemaItemPhysicalType)[keyof typeof ObjectAttributeSchemaItemPhysicalType];

export const ObjectAttributeSchemaItemPhysicalType = {
  number: "number",
  string: "string",
  boolean: "boolean",
  datetime: "datetime",
  unknown: "unknown",
} as const;

export type ObjectAttributeSchemaItemAnalyticalType =
  (typeof ObjectAttributeSchemaItemAnalyticalType)[keyof typeof ObjectAttributeSchemaItemAnalyticalType];

export const ObjectAttributeSchemaItemAnalyticalType = {
  categorical: "categorical",
  discrete: "discrete",
  continuous: "continuous",
  temporal: "temporal",
  unknown: "unknown",
} as const;

export type ObjectAttributeSchemaItemBehavior =
  (typeof ObjectAttributeSchemaItemBehavior)[keyof typeof ObjectAttributeSchemaItemBehavior];

export const ObjectAttributeSchemaItemBehavior = {
  static: "static",
  dynamic: "dynamic",
} as const;

export interface ObjectAttributeSchemaItem {
  name: string;
  physical_type: ObjectAttributeSchemaItemPhysicalType;
  analytical_type: ObjectAttributeSchemaItemAnalyticalType;
  present_count: number;
  missing_count: number;
  distinct_count: number;
  behavior: ObjectAttributeSchemaItemBehavior;
  initial_present_count: number;
  current_present_count: number;
  observed_value_count: number;
  change_count: number;
  changed_object_count: number;
}

export interface ObjectTypeSchemaItem {
  name: string;
  object_count: number;
  attributes: ObjectAttributeSchemaItem[];
}

export interface AnalyticalSchemaResponse {
  schema_version?: "1";
  activities: ActivitySchemaItem[];
  object_types: ObjectTypeSchemaItem[];
}

export interface CategoryGrouping {
  kind: "categories";
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
}

export type DistributionBucketKind =
  (typeof DistributionBucketKind)[keyof typeof DistributionBucketKind];

export const DistributionBucketKind = {
  value: "value",
  range: "range",
  missing: "missing",
  other: "other",
} as const;

export interface DistributionBucket {
  key: string;
  label: string;
  count: number;
  kind: DistributionBucketKind;
  value?: string | number | boolean | null;
  lower?: number | null;
  upper?: number | null;
  inclusive_upper?: boolean;
}

export interface QueryCounts {
  total: number;
  present: number;
  missing: number;
  represented: number;
}

export interface DistributionResponse {
  buckets: DistributionBucket[];
  counts: QueryCounts;
  truncated: boolean;
}

export interface NumericBinGrouping {
  kind: "bins";
  count?: number | null;
}

export interface EventAttributeDistributionQuery {
  activity: string;
  attribute: string;
  grouping: CategoryGrouping | NumericBinGrouping;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ObjectActivityExecutionDistributionQuery {
  object_type: string;
}

export interface ObjectActivityExecutionDistributionRow {
  activity: string;
  execution_count: number;
  object_count: number;
}

export interface ObjectActivityExecutionDistributionResponse {
  rows: ObjectActivityExecutionDistributionRow[];
  contributing_object_count: number;
  activity_count: number;
}

export interface ObjectAttributeDistributionOptionsResponse {
  pairs: ActivityObjectTypePair[];
}

export interface ObjectAttributeDistributionQuery {
  activity: string;
  object_type: string;
  attribute: string;
  grouping: CategoryGrouping | NumericBinGrouping;
}

export interface ObjectCountPerEventRow {
  activity: string;
  object_type: string;
  object_count: number;
  event_count: number;
}

export interface ObjectCountsPerEventQuery {
  activities?: string[];
}

export interface ObjectCountsPerEventResponse {
  rows: ObjectCountPerEventRow[];
  activity_event_counts: ActivityEventCount[];
}

export interface ObjectInvolvementDistributionQuery {
  activity: string;
  object_type: string;
  grouping: CategoryGrouping | NumericBinGrouping;
}

export interface ObjectInvolvementOption {
  activity: string;
  object_type: string;
  minimum: number;
  maximum: number;
}

export interface ObjectInvolvementOptionsResponse {
  pairs: ObjectInvolvementOption[];
}

export interface ObjectTypeCombinationRow {
  object_types: string[];
  activity: string;
  event_count: number;
}

export interface ObjectTypeCombinationsQuery {
  /**
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
  activities?: string[];
}

export interface ObjectTypeCombinationsResponse {
  rows: ObjectTypeCombinationRow[];
  total_event_count: number;
  represented_event_count: number;
  total_combination_count: number;
  truncated: boolean;
}

export type TimeBetweenActivitiesQueryUnit =
  (typeof TimeBetweenActivitiesQueryUnit)[keyof typeof TimeBetweenActivitiesQueryUnit];

export const TimeBetweenActivitiesQueryUnit = {
  seconds: "seconds",
  minutes: "minutes",
  hours: "hours",
  days: "days",
} as const;

export interface TimeBetweenActivitiesQuery {
  source_activity: string;
  target_activity: string;
  object_type: string;
  unit: TimeBetweenActivitiesQueryUnit;
  bin_count?: number | null;
}

export type TimeBetweenActivitiesResponseUnit =
  (typeof TimeBetweenActivitiesResponseUnit)[keyof typeof TimeBetweenActivitiesResponseUnit];

export const TimeBetweenActivitiesResponseUnit = {
  seconds: "seconds",
  minutes: "minutes",
  hours: "hours",
  days: "days",
} as const;

export interface TimeBetweenActivitiesResponse {
  buckets: DistributionBucket[];
  counts: QueryCounts;
  truncated: boolean;
  unit: TimeBetweenActivitiesResponseUnit;
  pair_count: number;
  contributing_object_count: number;
}

export interface TotalObjectInvolvementRow {
  activity: string;
  object_count: number;
  event_count: number;
}

export interface TotalObjectInvolvementResponse {
  rows: TotalObjectInvolvementRow[];
  event_count: number;
}

export type QueryEventAttributeDistributionParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryObjectAttributeDistributionParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryObjectCountsPerEventParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryObjectTypeCombinationsParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryActivityExecutionFrequencyParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryObjectInvolvementDistributionParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryTimeBetweenActivitiesParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryObjectActivityExecutionDistributionParams = {
  ocel_version?: "original" | "filtered" | null;
};

export type QueryTotalObjectInvolvementParams = {
  ocel_version?: "original" | "filtered" | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get Analytical Schema
 */
export const getAnalyticalSchema = (
  ocelId: string | null,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<AnalyticalSchemaResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/analytical-schema`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetAnalyticalSchemaQueryKey = (ocelId: string | null) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/analytical-schema`,
  ] as const;
};

export const getGetAnalyticalSchemaQueryOptions = <
  TData = Awaited<ReturnType<typeof getAnalyticalSchema>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnalyticalSchema>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAnalyticalSchemaQueryKey(ocelId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAnalyticalSchema>>
  > = ({ signal }) => getAnalyticalSchema(ocelId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAnalyticalSchema>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAnalyticalSchemaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAnalyticalSchema>>
>;
export type GetAnalyticalSchemaQueryError = HTTPValidationError;

export function useGetAnalyticalSchema<
  TData = Awaited<ReturnType<typeof getAnalyticalSchema>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnalyticalSchema>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticalSchema>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticalSchema>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAnalyticalSchema<
  TData = Awaited<ReturnType<typeof getAnalyticalSchema>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnalyticalSchema>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticalSchema>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticalSchema>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAnalyticalSchema<
  TData = Awaited<ReturnType<typeof getAnalyticalSchema>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnalyticalSchema>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Analytical Schema
 */

export function useGetAnalyticalSchema<
  TData = Awaited<ReturnType<typeof getAnalyticalSchema>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAnalyticalSchema>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAnalyticalSchemaQueryOptions(ocelId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Event Attribute Distribution
 */
export const queryEventAttributeDistribution = (
  ocelId: string | null,
  eventAttributeDistributionQuery: EventAttributeDistributionQuery,
  params?: QueryEventAttributeDistributionParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<DistributionResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/event-attribute-distribution`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: eventAttributeDistributionQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryEventAttributeDistributionQueryKey = (
  ocelId: string | null,
  eventAttributeDistributionQuery?: EventAttributeDistributionQuery,
  params?: QueryEventAttributeDistributionParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/event-attribute-distribution`,
    ...(params ? [params] : []),
    eventAttributeDistributionQuery,
  ] as const;
};

export const getQueryEventAttributeDistributionQueryOptions = <
  TData = Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  eventAttributeDistributionQuery: EventAttributeDistributionQuery,
  params?: QueryEventAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryEventAttributeDistributionQueryKey(
      ocelId,
      eventAttributeDistributionQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryEventAttributeDistribution>>
  > = ({ signal }) =>
    queryEventAttributeDistribution(
      ocelId,
      eventAttributeDistributionQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryEventAttributeDistributionQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryEventAttributeDistribution>>
>;
export type QueryEventAttributeDistributionQueryError = HTTPValidationError;

export function useQueryEventAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  eventAttributeDistributionQuery: EventAttributeDistributionQuery,
  params: undefined | QueryEventAttributeDistributionParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryEventAttributeDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryEventAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  eventAttributeDistributionQuery: EventAttributeDistributionQuery,
  params?: QueryEventAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryEventAttributeDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryEventAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  eventAttributeDistributionQuery: EventAttributeDistributionQuery,
  params?: QueryEventAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Event Attribute Distribution
 */

export function useQueryEventAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  eventAttributeDistributionQuery: EventAttributeDistributionQuery,
  params?: QueryEventAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryEventAttributeDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryEventAttributeDistributionQueryOptions(
    ocelId,
    eventAttributeDistributionQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Object Attribute Distribution Options
 */
export const getObjectAttributeDistributionOptions = (
  ocelId: string | null,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<ObjectAttributeDistributionOptionsResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution/options`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetObjectAttributeDistributionOptionsQueryKey = (
  ocelId: string | null,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution/options`,
  ] as const;
};

export const getGetObjectAttributeDistributionOptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetObjectAttributeDistributionOptionsQueryKey(ocelId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>
  > = ({ signal }) =>
    getObjectAttributeDistributionOptions(ocelId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetObjectAttributeDistributionOptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>
>;
export type GetObjectAttributeDistributionOptionsQueryError =
  HTTPValidationError;

export function useGetObjectAttributeDistributionOptions<
  TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetObjectAttributeDistributionOptions<
  TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetObjectAttributeDistributionOptions<
  TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Object Attribute Distribution Options
 */

export function useGetObjectAttributeDistributionOptions<
  TData = Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectAttributeDistributionOptions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetObjectAttributeDistributionOptionsQueryOptions(
    ocelId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Object Attribute Distribution
 */
export const queryObjectAttributeDistribution = (
  ocelId: string | null,
  objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
  params?: QueryObjectAttributeDistributionParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<DistributionResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: objectAttributeDistributionQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryObjectAttributeDistributionQueryKey = (
  ocelId: string | null,
  objectAttributeDistributionQuery?: ObjectAttributeDistributionQuery,
  params?: QueryObjectAttributeDistributionParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-attribute-distribution`,
    ...(params ? [params] : []),
    objectAttributeDistributionQuery,
  ] as const;
};

export const getQueryObjectAttributeDistributionQueryOptions = <
  TData = Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
  params?: QueryObjectAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryObjectAttributeDistributionQueryKey(
      ocelId,
      objectAttributeDistributionQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryObjectAttributeDistribution>>
  > = ({ signal }) =>
    queryObjectAttributeDistribution(
      ocelId,
      objectAttributeDistributionQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryObjectAttributeDistributionQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryObjectAttributeDistribution>>
>;
export type QueryObjectAttributeDistributionQueryError = HTTPValidationError;

export function useQueryObjectAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
  params: undefined | QueryObjectAttributeDistributionParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryObjectAttributeDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
  params?: QueryObjectAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryObjectAttributeDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
  params?: QueryObjectAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Object Attribute Distribution
 */

export function useQueryObjectAttributeDistribution<
  TData = Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectAttributeDistributionQuery: ObjectAttributeDistributionQuery,
  params?: QueryObjectAttributeDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectAttributeDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryObjectAttributeDistributionQueryOptions(
    ocelId,
    objectAttributeDistributionQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Object Counts Per Event
 */
export const queryObjectCountsPerEvent = (
  ocelId: string | null,
  objectCountsPerEventQuery: ObjectCountsPerEventQuery,
  params?: QueryObjectCountsPerEventParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<ObjectCountsPerEventResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-counts-per-event`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: objectCountsPerEventQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryObjectCountsPerEventQueryKey = (
  ocelId: string | null,
  objectCountsPerEventQuery?: ObjectCountsPerEventQuery,
  params?: QueryObjectCountsPerEventParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-counts-per-event`,
    ...(params ? [params] : []),
    objectCountsPerEventQuery,
  ] as const;
};

export const getQueryObjectCountsPerEventQueryOptions = <
  TData = Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectCountsPerEventQuery: ObjectCountsPerEventQuery,
  params?: QueryObjectCountsPerEventParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryObjectCountsPerEventQueryKey(
      ocelId,
      objectCountsPerEventQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryObjectCountsPerEvent>>
  > = ({ signal }) =>
    queryObjectCountsPerEvent(
      ocelId,
      objectCountsPerEventQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryObjectCountsPerEventQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryObjectCountsPerEvent>>
>;
export type QueryObjectCountsPerEventQueryError = HTTPValidationError;

export function useQueryObjectCountsPerEvent<
  TData = Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectCountsPerEventQuery: ObjectCountsPerEventQuery,
  params: undefined | QueryObjectCountsPerEventParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
          TError,
          Awaited<ReturnType<typeof queryObjectCountsPerEvent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectCountsPerEvent<
  TData = Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectCountsPerEventQuery: ObjectCountsPerEventQuery,
  params?: QueryObjectCountsPerEventParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
          TError,
          Awaited<ReturnType<typeof queryObjectCountsPerEvent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectCountsPerEvent<
  TData = Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectCountsPerEventQuery: ObjectCountsPerEventQuery,
  params?: QueryObjectCountsPerEventParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Object Counts Per Event
 */

export function useQueryObjectCountsPerEvent<
  TData = Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectCountsPerEventQuery: ObjectCountsPerEventQuery,
  params?: QueryObjectCountsPerEventParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectCountsPerEvent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryObjectCountsPerEventQueryOptions(
    ocelId,
    objectCountsPerEventQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Object Type Combinations
 */
export const queryObjectTypeCombinations = (
  ocelId: string | null,
  objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
  params?: QueryObjectTypeCombinationsParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<ObjectTypeCombinationsResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-type-combinations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: objectTypeCombinationsQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryObjectTypeCombinationsQueryKey = (
  ocelId: string | null,
  objectTypeCombinationsQuery?: ObjectTypeCombinationsQuery,
  params?: QueryObjectTypeCombinationsParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-type-combinations`,
    ...(params ? [params] : []),
    objectTypeCombinationsQuery,
  ] as const;
};

export const getQueryObjectTypeCombinationsQueryOptions = <
  TData = Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
  params?: QueryObjectTypeCombinationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryObjectTypeCombinationsQueryKey(
      ocelId,
      objectTypeCombinationsQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryObjectTypeCombinations>>
  > = ({ signal }) =>
    queryObjectTypeCombinations(
      ocelId,
      objectTypeCombinationsQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryObjectTypeCombinationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryObjectTypeCombinations>>
>;
export type QueryObjectTypeCombinationsQueryError = HTTPValidationError;

export function useQueryObjectTypeCombinations<
  TData = Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
  params: undefined | QueryObjectTypeCombinationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
          TError,
          Awaited<ReturnType<typeof queryObjectTypeCombinations>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectTypeCombinations<
  TData = Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
  params?: QueryObjectTypeCombinationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
          TError,
          Awaited<ReturnType<typeof queryObjectTypeCombinations>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectTypeCombinations<
  TData = Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
  params?: QueryObjectTypeCombinationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Object Type Combinations
 */

export function useQueryObjectTypeCombinations<
  TData = Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectTypeCombinationsQuery: ObjectTypeCombinationsQuery,
  params?: QueryObjectTypeCombinationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectTypeCombinations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryObjectTypeCombinationsQueryOptions(
    ocelId,
    objectTypeCombinationsQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Activity Execution Frequency
 */
export const queryActivityExecutionFrequency = (
  ocelId: string | null,
  activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
  params?: QueryActivityExecutionFrequencyParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<ActivityExecutionFrequencyResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/activity-execution-frequency`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: activityExecutionFrequencyQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryActivityExecutionFrequencyQueryKey = (
  ocelId: string | null,
  activityExecutionFrequencyQuery?: ActivityExecutionFrequencyQuery,
  params?: QueryActivityExecutionFrequencyParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/activity-execution-frequency`,
    ...(params ? [params] : []),
    activityExecutionFrequencyQuery,
  ] as const;
};

export const getQueryActivityExecutionFrequencyQueryOptions = <
  TData = Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
  params?: QueryActivityExecutionFrequencyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryActivityExecutionFrequencyQueryKey(
      ocelId,
      activityExecutionFrequencyQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryActivityExecutionFrequency>>
  > = ({ signal }) =>
    queryActivityExecutionFrequency(
      ocelId,
      activityExecutionFrequencyQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryActivityExecutionFrequencyQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryActivityExecutionFrequency>>
>;
export type QueryActivityExecutionFrequencyQueryError = HTTPValidationError;

export function useQueryActivityExecutionFrequency<
  TData = Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
  params: undefined | QueryActivityExecutionFrequencyParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
          TError,
          Awaited<ReturnType<typeof queryActivityExecutionFrequency>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryActivityExecutionFrequency<
  TData = Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
  params?: QueryActivityExecutionFrequencyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
          TError,
          Awaited<ReturnType<typeof queryActivityExecutionFrequency>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryActivityExecutionFrequency<
  TData = Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
  params?: QueryActivityExecutionFrequencyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Activity Execution Frequency
 */

export function useQueryActivityExecutionFrequency<
  TData = Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  activityExecutionFrequencyQuery: ActivityExecutionFrequencyQuery,
  params?: QueryActivityExecutionFrequencyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryActivityExecutionFrequency>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryActivityExecutionFrequencyQueryOptions(
    ocelId,
    activityExecutionFrequencyQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Object Involvement Options
 */
export const getObjectInvolvementOptions = (
  ocelId: string | null,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<ObjectInvolvementOptionsResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution/options`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetObjectInvolvementOptionsQueryKey = (
  ocelId: string | null,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution/options`,
  ] as const;
};

export const getGetObjectInvolvementOptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetObjectInvolvementOptionsQueryKey(ocelId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getObjectInvolvementOptions>>
  > = ({ signal }) =>
    getObjectInvolvementOptions(ocelId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetObjectInvolvementOptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getObjectInvolvementOptions>>
>;
export type GetObjectInvolvementOptionsQueryError = HTTPValidationError;

export function useGetObjectInvolvementOptions<
  TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetObjectInvolvementOptions<
  TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
          TError,
          Awaited<ReturnType<typeof getObjectInvolvementOptions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetObjectInvolvementOptions<
  TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Object Involvement Options
 */

export function useGetObjectInvolvementOptions<
  TData = Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getObjectInvolvementOptions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetObjectInvolvementOptionsQueryOptions(
    ocelId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Object Involvement Distribution
 */
export const queryObjectInvolvementDistribution = (
  ocelId: string | null,
  objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
  params?: QueryObjectInvolvementDistributionParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<DistributionResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: objectInvolvementDistributionQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryObjectInvolvementDistributionQueryKey = (
  ocelId: string | null,
  objectInvolvementDistributionQuery?: ObjectInvolvementDistributionQuery,
  params?: QueryObjectInvolvementDistributionParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-involvement-distribution`,
    ...(params ? [params] : []),
    objectInvolvementDistributionQuery,
  ] as const;
};

export const getQueryObjectInvolvementDistributionQueryOptions = <
  TData = Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
  params?: QueryObjectInvolvementDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryObjectInvolvementDistributionQueryKey(
      ocelId,
      objectInvolvementDistributionQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>
  > = ({ signal }) =>
    queryObjectInvolvementDistribution(
      ocelId,
      objectInvolvementDistributionQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryObjectInvolvementDistributionQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>
>;
export type QueryObjectInvolvementDistributionQueryError = HTTPValidationError;

export function useQueryObjectInvolvementDistribution<
  TData = Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
  params: undefined | QueryObjectInvolvementDistributionParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectInvolvementDistribution<
  TData = Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
  params?: QueryObjectInvolvementDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectInvolvementDistribution<
  TData = Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
  params?: QueryObjectInvolvementDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Object Involvement Distribution
 */

export function useQueryObjectInvolvementDistribution<
  TData = Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectInvolvementDistributionQuery: ObjectInvolvementDistributionQuery,
  params?: QueryObjectInvolvementDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectInvolvementDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryObjectInvolvementDistributionQueryOptions(
    ocelId,
    objectInvolvementDistributionQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Time Between Activities
 */
export const queryTimeBetweenActivities = (
  ocelId: string | null,
  timeBetweenActivitiesQuery: TimeBetweenActivitiesQuery,
  params?: QueryTimeBetweenActivitiesParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<TimeBetweenActivitiesResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/time-between-activities`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: timeBetweenActivitiesQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryTimeBetweenActivitiesQueryKey = (
  ocelId: string | null,
  timeBetweenActivitiesQuery?: TimeBetweenActivitiesQuery,
  params?: QueryTimeBetweenActivitiesParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/time-between-activities`,
    ...(params ? [params] : []),
    timeBetweenActivitiesQuery,
  ] as const;
};

export const getQueryTimeBetweenActivitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  timeBetweenActivitiesQuery: TimeBetweenActivitiesQuery,
  params?: QueryTimeBetweenActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryTimeBetweenActivitiesQueryKey(
      ocelId,
      timeBetweenActivitiesQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryTimeBetweenActivities>>
  > = ({ signal }) =>
    queryTimeBetweenActivities(
      ocelId,
      timeBetweenActivitiesQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryTimeBetweenActivitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryTimeBetweenActivities>>
>;
export type QueryTimeBetweenActivitiesQueryError = HTTPValidationError;

export function useQueryTimeBetweenActivities<
  TData = Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  timeBetweenActivitiesQuery: TimeBetweenActivitiesQuery,
  params: undefined | QueryTimeBetweenActivitiesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
          TError,
          Awaited<ReturnType<typeof queryTimeBetweenActivities>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryTimeBetweenActivities<
  TData = Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  timeBetweenActivitiesQuery: TimeBetweenActivitiesQuery,
  params?: QueryTimeBetweenActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
          TError,
          Awaited<ReturnType<typeof queryTimeBetweenActivities>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryTimeBetweenActivities<
  TData = Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  timeBetweenActivitiesQuery: TimeBetweenActivitiesQuery,
  params?: QueryTimeBetweenActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Time Between Activities
 */

export function useQueryTimeBetweenActivities<
  TData = Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  timeBetweenActivitiesQuery: TimeBetweenActivitiesQuery,
  params?: QueryTimeBetweenActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTimeBetweenActivities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryTimeBetweenActivitiesQueryOptions(
    ocelId,
    timeBetweenActivitiesQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Object Activity Execution Distribution
 */
export const queryObjectActivityExecutionDistribution = (
  ocelId: string | null,
  objectActivityExecutionDistributionQuery: ObjectActivityExecutionDistributionQuery,
  params?: QueryObjectActivityExecutionDistributionParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<ObjectActivityExecutionDistributionResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-activity-execution-distribution`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: objectActivityExecutionDistributionQuery,
      params,
      signal,
    },
    options,
  );
};

export const getQueryObjectActivityExecutionDistributionQueryKey = (
  ocelId: string | null,
  objectActivityExecutionDistributionQuery?: ObjectActivityExecutionDistributionQuery,
  params?: QueryObjectActivityExecutionDistributionParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/object-activity-execution-distribution`,
    ...(params ? [params] : []),
    objectActivityExecutionDistributionQuery,
  ] as const;
};

export const getQueryObjectActivityExecutionDistributionQueryOptions = <
  TData = Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectActivityExecutionDistributionQuery: ObjectActivityExecutionDistributionQuery,
  params?: QueryObjectActivityExecutionDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryObjectActivityExecutionDistributionQueryKey(
      ocelId,
      objectActivityExecutionDistributionQuery,
      params,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>
  > = ({ signal }) =>
    queryObjectActivityExecutionDistribution(
      ocelId,
      objectActivityExecutionDistributionQuery,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryObjectActivityExecutionDistributionQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>
>;
export type QueryObjectActivityExecutionDistributionQueryError =
  HTTPValidationError;

export function useQueryObjectActivityExecutionDistribution<
  TData = Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectActivityExecutionDistributionQuery: ObjectActivityExecutionDistributionQuery,
  params: undefined | QueryObjectActivityExecutionDistributionParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectActivityExecutionDistribution<
  TData = Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectActivityExecutionDistributionQuery: ObjectActivityExecutionDistributionQuery,
  params?: QueryObjectActivityExecutionDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
          TError,
          Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryObjectActivityExecutionDistribution<
  TData = Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectActivityExecutionDistributionQuery: ObjectActivityExecutionDistributionQuery,
  params?: QueryObjectActivityExecutionDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Object Activity Execution Distribution
 */

export function useQueryObjectActivityExecutionDistribution<
  TData = Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  objectActivityExecutionDistributionQuery: ObjectActivityExecutionDistributionQuery,
  params?: QueryObjectActivityExecutionDistributionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryObjectActivityExecutionDistribution>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryObjectActivityExecutionDistributionQueryOptions(
    ocelId,
    objectActivityExecutionDistributionQuery,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Query Total Object Involvement
 */
export const queryTotalObjectInvolvement = (
  ocelId: string | null,
  params?: QueryTotalObjectInvolvementParams,
  options?: SecondParameter<typeof customFetch>,
  signal?: AbortSignal,
) => {
  return customFetch<TotalObjectInvolvementResponse>(
    {
      url: `/api/external/modules/querying/v1/ocels/${ocelId}/queries/total-object-involvement`,
      method: "POST",
      params,
      signal,
    },
    options,
  );
};

export const getQueryTotalObjectInvolvementQueryKey = (
  ocelId: string | null,
  params?: QueryTotalObjectInvolvementParams,
) => {
  return [
    `/api/external/modules/querying/v1/ocels/${ocelId}/queries/total-object-involvement`,
    ...(params ? [params] : []),
  ] as const;
};

export const getQueryTotalObjectInvolvementQueryOptions = <
  TData = Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  params?: QueryTotalObjectInvolvementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getQueryTotalObjectInvolvementQueryKey(ocelId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof queryTotalObjectInvolvement>>
  > = ({ signal }) =>
    queryTotalObjectInvolvement(ocelId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!ocelId,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QueryTotalObjectInvolvementQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryTotalObjectInvolvement>>
>;
export type QueryTotalObjectInvolvementQueryError = HTTPValidationError;

export function useQueryTotalObjectInvolvement<
  TData = Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  params: undefined | QueryTotalObjectInvolvementParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
          TError,
          Awaited<ReturnType<typeof queryTotalObjectInvolvement>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryTotalObjectInvolvement<
  TData = Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  params?: QueryTotalObjectInvolvementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
          TError,
          Awaited<ReturnType<typeof queryTotalObjectInvolvement>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useQueryTotalObjectInvolvement<
  TData = Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  params?: QueryTotalObjectInvolvementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Query Total Object Involvement
 */

export function useQueryTotalObjectInvolvement<
  TData = Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
  TError = HTTPValidationError,
>(
  ocelId: string | null,
  params?: QueryTotalObjectInvolvementParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof queryTotalObjectInvolvement>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getQueryTotalObjectInvolvementQueryOptions(
    ocelId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
