import matplotlib

from ocelescope.ocel import (
    OCEL,
    BaseFilter,
    E2OCountFilter,
    EventAttributeFilter,
    EventTypeFilter,
    ObjectIdFilter,
    EventTypeFrequencyFilter,
    O2OCountFilter,
    ObjectAttributeFilter,
    ObjectTypeFilter,
    ObjectTypeFrequencyFilter,
    OCELExtension,
    TimeFrameFilter,
)
from ocelescope.plugin import (
    CODE_FIELD,
    COMPUTED_SELECTION,
    OCEL_FIELD,
    OCELAnnotation,
    Plugin,
    PluginInput,
    PluginMeta,
    PluginMethod,
    PluginResult,
    ResourceAnnotation,
    SQL_FIELD,
    plugin_method,
)
from ocelescope.resource import DirectlyFollowsGraph, PetriNet, Resource
from ocelescope.visualization import (
    DIRECTED_ELK_GRAPH_LAYOUT,
    DIRECTED_GRAPH_LAYOUT,
    FORCE_GRAPH_LAYOUT,
    ORDERED_TREE_LAYOUT,
    RADIAL_GRAPH_LAYOUT,
    DotVis,
    EdgeArrow,
    ElkLayoutConfig,
    Graph,
    GraphEdge,
    GraphNode,
    GraphShapes,
    GraphvizLayoutConfig,
    LayoutConfig,
    SVGVis,
    Table,
    TableColumn,
    Visualization,
    generate_color_map,
)

matplotlib.use("Agg")

__all__ = [
    "OCEL",
    "OCELExtension",
    "E2OCountFilter",
    "EventAttributeFilter",
    "EventTypeFilter",
    "ObjectIdFilter",
    "EventTypeFrequencyFilter",
    "O2OCountFilter",
    "ObjectAttributeFilter",
    "ObjectTypeFilter",
    "ObjectTypeFrequencyFilter",
    "TimeFrameFilter",
    "Visualization",
    "PetriNet",
    "DirectlyFollowsGraph",
    "Resource",
    "ResourceAnnotation",
    "OCELAnnotation",
    "Plugin",
    "PluginMeta",
    "PluginMethod",
    "COMPUTED_SELECTION",
    "OCEL_FIELD",
    "CODE_FIELD",
    "SQL_FIELD",
    "PluginInput",
    "PluginResult",
    "plugin_method",
    "BaseFilter",
    # Visualization
    # Util
    "Visualization",
    "generate_color_map",
    # Graph
    "Graph",
    "GraphNode",
    "GraphEdge",
    "EdgeArrow",
    "LayoutConfig",
    "ElkLayoutConfig",
    "GraphvizLayoutConfig",
    "GraphShapes",
    "DIRECTED_ELK_GRAPH_LAYOUT",
    "DIRECTED_GRAPH_LAYOUT",
    "FORCE_GRAPH_LAYOUT",
    "ORDERED_TREE_LAYOUT",
    "RADIAL_GRAPH_LAYOUT",
    # Table
    "Table",
    "TableColumn",
    # SVG
    "SVGVis",
    # Graphviz
    "DotVis",
]
