/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPluginTasksParams,
  GetSystemTasksParams,
  HTTPValidationError,
  PluginTaskSummary,
  SystemTaskSummary
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary returns all tasks of a session
 */
export const getGetSystemTasksUrl = (params?: GetSystemTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/tasks/system?${stringifiedParams}` : `http://localhost:8000/tasks/system`
}

export const getSystemTasks = async (params?: GetSystemTasksParams, options?: RequestInit): Promise<SystemTaskSummary[]> => {
  
  return customFetch<SystemTaskSummary[]>(getGetSystemTasksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetSystemTasksQueryKey = (params?: GetSystemTasksParams,) => {
    return [`http://localhost:8000/tasks/system`, ...(params ? [params]: [])] as const;
    }

    
export const getGetSystemTasksQueryOptions = <TData = Awaited<ReturnType<typeof getSystemTasks>>, TError = HTTPValidationError>(params?: GetSystemTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemTasksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemTasks>>> = ({ signal }) => getSystemTasks(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemTasks>>>
export type GetSystemTasksQueryError = HTTPValidationError


export function useGetSystemTasks<TData = Awaited<ReturnType<typeof getSystemTasks>>, TError = HTTPValidationError>(
 params: undefined |  GetSystemTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemTasks>>,
          TError,
          Awaited<ReturnType<typeof getSystemTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemTasks<TData = Awaited<ReturnType<typeof getSystemTasks>>, TError = HTTPValidationError>(
 params?: GetSystemTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemTasks>>,
          TError,
          Awaited<ReturnType<typeof getSystemTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemTasks<TData = Awaited<ReturnType<typeof getSystemTasks>>, TError = HTTPValidationError>(
 params?: GetSystemTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary returns all tasks of a session
 */

export function useGetSystemTasks<TData = Awaited<ReturnType<typeof getSystemTasks>>, TError = HTTPValidationError>(
 params?: GetSystemTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemTasksQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary returns the task of a given taskId
 */
export const getGetSystemTaskUrl = (taskId: string,) => {


  

  return `http://localhost:8000/tasks/system/${taskId}`
}

export const getSystemTask = async (taskId: string, options?: RequestInit): Promise<SystemTaskSummary> => {
  
  return customFetch<SystemTaskSummary>(getGetSystemTaskUrl(taskId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetSystemTaskQueryKey = (taskId: string,) => {
    return [`http://localhost:8000/tasks/system/${taskId}`] as const;
    }

    
export const getGetSystemTaskQueryOptions = <TData = Awaited<ReturnType<typeof getSystemTask>>, TError = HTTPValidationError>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemTaskQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemTask>>> = ({ signal }) => getSystemTask(taskId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemTask>>>
export type GetSystemTaskQueryError = HTTPValidationError


export function useGetSystemTask<TData = Awaited<ReturnType<typeof getSystemTask>>, TError = HTTPValidationError>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemTask>>,
          TError,
          Awaited<ReturnType<typeof getSystemTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemTask<TData = Awaited<ReturnType<typeof getSystemTask>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemTask>>,
          TError,
          Awaited<ReturnType<typeof getSystemTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemTask<TData = Awaited<ReturnType<typeof getSystemTask>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary returns the task of a given taskId
 */

export function useGetSystemTask<TData = Awaited<ReturnType<typeof getSystemTask>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemTaskQueryOptions(taskId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary returns all tasks of a session
 */
export const getGetPluginTasksUrl = (params: GetPluginTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/tasks/plugin?${stringifiedParams}` : `http://localhost:8000/tasks/plugin`
}

export const getPluginTasks = async (params: GetPluginTasksParams, options?: RequestInit): Promise<PluginTaskSummary[]> => {
  
  return customFetch<PluginTaskSummary[]>(getGetPluginTasksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetPluginTasksQueryKey = (params: GetPluginTasksParams,) => {
    return [`http://localhost:8000/tasks/plugin`, ...(params ? [params]: [])] as const;
    }

    
export const getGetPluginTasksQueryOptions = <TData = Awaited<ReturnType<typeof getPluginTasks>>, TError = HTTPValidationError>(params: GetPluginTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPluginTasksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPluginTasks>>> = ({ signal }) => getPluginTasks(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPluginTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPluginTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getPluginTasks>>>
export type GetPluginTasksQueryError = HTTPValidationError


export function useGetPluginTasks<TData = Awaited<ReturnType<typeof getPluginTasks>>, TError = HTTPValidationError>(
 params: GetPluginTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPluginTasks>>,
          TError,
          Awaited<ReturnType<typeof getPluginTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPluginTasks<TData = Awaited<ReturnType<typeof getPluginTasks>>, TError = HTTPValidationError>(
 params: GetPluginTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPluginTasks>>,
          TError,
          Awaited<ReturnType<typeof getPluginTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPluginTasks<TData = Awaited<ReturnType<typeof getPluginTasks>>, TError = HTTPValidationError>(
 params: GetPluginTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary returns all tasks of a session
 */

export function useGetPluginTasks<TData = Awaited<ReturnType<typeof getPluginTasks>>, TError = HTTPValidationError>(
 params: GetPluginTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPluginTasksQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary returns the task of a given taskId
 */
export const getGetPluginTaskUrl = (taskId: string,) => {


  

  return `http://localhost:8000/tasks/plugin/${taskId}`
}

export const getPluginTask = async (taskId: string, options?: RequestInit): Promise<PluginTaskSummary> => {
  
  return customFetch<PluginTaskSummary>(getGetPluginTaskUrl(taskId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetPluginTaskQueryKey = (taskId: string,) => {
    return [`http://localhost:8000/tasks/plugin/${taskId}`] as const;
    }

    
export const getGetPluginTaskQueryOptions = <TData = Awaited<ReturnType<typeof getPluginTask>>, TError = HTTPValidationError>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPluginTaskQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPluginTask>>> = ({ signal }) => getPluginTask(taskId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPluginTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPluginTaskQueryResult = NonNullable<Awaited<ReturnType<typeof getPluginTask>>>
export type GetPluginTaskQueryError = HTTPValidationError


export function useGetPluginTask<TData = Awaited<ReturnType<typeof getPluginTask>>, TError = HTTPValidationError>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPluginTask>>,
          TError,
          Awaited<ReturnType<typeof getPluginTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPluginTask<TData = Awaited<ReturnType<typeof getPluginTask>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPluginTask>>,
          TError,
          Awaited<ReturnType<typeof getPluginTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPluginTask<TData = Awaited<ReturnType<typeof getPluginTask>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary returns the task of a given taskId
 */

export function useGetPluginTask<TData = Awaited<ReturnType<typeof getPluginTask>>, TError = HTTPValidationError>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPluginTaskQueryOptions(taskId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



