/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadResource,
  GetResourceResponse,
  HTTPValidationError,
  RenameResourceParams,
  ResourceApi
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Outputs
 */
export const getResourcesUrl = () => {


  

  return `http://localhost:8000/resources/`
}

export const resources = async ( options?: RequestInit): Promise<ResourceApi[]> => {
  
  return customFetch<ResourceApi[]>(getResourcesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getResourcesQueryKey = () => {
    return [`http://localhost:8000/resources/`] as const;
    }

    
export const getResourcesQueryOptions = <TData = Awaited<ReturnType<typeof resources>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResourcesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resources>>> = ({ signal }) => resources({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof resources>>>
export type ResourcesQueryError = unknown


export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resources>>,
          TError,
          Awaited<ReturnType<typeof resources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resources>>,
          TError,
          Awaited<ReturnType<typeof resources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Outputs
 */

export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResourcesQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Upload Resource
 */
export const getUploadResourceUrl = () => {


  

  return `http://localhost:8000/resources/`
}

export const uploadResource = async (bodyUploadResource: BodyUploadResource, options?: RequestInit): Promise<unknown> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadResource.file)

  return customFetch<unknown>(getUploadResourceUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadResource>>, TError,{data: BodyUploadResource}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadResource>>, TError,{data: BodyUploadResource}, TContext> => {

const mutationKey = ['uploadResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadResource>>, {data: BodyUploadResource}> = (props) => {
          const {data} = props ?? {};

          return  uploadResource(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadResourceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadResource>>>
    export type UploadResourceMutationBody = BodyUploadResource
    export type UploadResourceMutationError = HTTPValidationError

    /**
 * @summary Upload Resource
 */
export const useUploadResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadResource>>, TError,{data: BodyUploadResource}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadResource>>,
        TError,
        {data: BodyUploadResource},
        TContext
      > => {

      const mutationOptions = getUploadResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Download Output
 */
export const getDownloadOutputResourcesResourceIdDownloadGetUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/${resourceId}/download`
}

export const downloadOutputResourcesResourceIdDownloadGet = async (resourceId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDownloadOutputResourcesResourceIdDownloadGetUrl(resourceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getDownloadOutputResourcesResourceIdDownloadGetQueryKey = (resourceId: string,) => {
    return [`http://localhost:8000/resources/${resourceId}/download`] as const;
    }

    
export const getDownloadOutputResourcesResourceIdDownloadGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadOutputResourcesResourceIdDownloadGetQueryKey(resourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>> = ({ signal }) => downloadOutputResourcesResourceIdDownloadGet(resourceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(resourceId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadOutputResourcesResourceIdDownloadGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>>
export type DownloadOutputResourcesResourceIdDownloadGetQueryError = HTTPValidationError


export function useDownloadOutputResourcesResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadOutputResourcesResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadOutputResourcesResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Output
 */

export function useDownloadOutputResourcesResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadOutputResourcesResourceIdDownloadGetQueryOptions(resourceId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Resource
 */
export const getResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/${resourceId}`
}

export const resource = async (resourceId: string, options?: RequestInit): Promise<GetResourceResponse> => {
  
  return customFetch<GetResourceResponse>(getResourceUrl(resourceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getResourceQueryKey = (resourceId: string,) => {
    return [`http://localhost:8000/resources/${resourceId}`] as const;
    }

    
export const getResourceQueryOptions = <TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResourceQueryKey(resourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resource>>> = ({ signal }) => resource(resourceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(resourceId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResourceQueryResult = NonNullable<Awaited<ReturnType<typeof resource>>>
export type ResourceQueryError = HTTPValidationError


export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resource>>,
          TError,
          Awaited<ReturnType<typeof resource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resource>>,
          TError,
          Awaited<ReturnType<typeof resource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Resource
 */

export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResourceQueryOptions(resourceId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Resource
 */
export const getDeleteResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/${resourceId}`
}

export const deleteResource = async (resourceId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDeleteResourceUrl(resourceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['deleteResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteResource>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  deleteResource(resourceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteResourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteResource>>>
    
    export type DeleteResourceMutationError = HTTPValidationError

    /**
 * @summary Delete Resource
 */
export const useDeleteResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteResource>>,
        TError,
        {resourceId: string},
        TContext
      > => {

      const mutationOptions = getDeleteResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Rename Resource
 */
export const getRenameResourceUrl = (outputId: string,
    params: RenameResourceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/resources/${outputId}?${stringifiedParams}` : `http://localhost:8000/resources/${outputId}`
}

export const renameResource = async (outputId: string,
    params: RenameResourceParams, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getRenameResourceUrl(outputId,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRenameResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameResource>>, TError,{outputId: string;params: RenameResourceParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof renameResource>>, TError,{outputId: string;params: RenameResourceParams}, TContext> => {

const mutationKey = ['renameResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameResource>>, {outputId: string;params: RenameResourceParams}> = (props) => {
          const {outputId,params} = props ?? {};

          return  renameResource(outputId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RenameResourceMutationResult = NonNullable<Awaited<ReturnType<typeof renameResource>>>
    
    export type RenameResourceMutationError = HTTPValidationError

    /**
 * @summary Rename Resource
 */
export const useRenameResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameResource>>, TError,{outputId: string;params: RenameResourceParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameResource>>,
        TError,
        {outputId: string;params: RenameResourceParams},
        TContext
      > => {

      const mutationOptions = getRenameResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    