/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadResource,
  GetResourceMeta200,
  GetResourceResponse,
  HTTPValidationError,
  RenameResourceParams,
  ResourceApi,
  ResourcesParams
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Resources
 */
export const getResourcesUrl = (params?: ResourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/resources/?${stringifiedParams}` : `http://localhost:8000/resources/`
}

export const resources = async (params?: ResourcesParams, options?: RequestInit): Promise<ResourceApi[]> => {
  
  return customFetch<ResourceApi[]>(getResourcesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getResourcesQueryKey = (params?: ResourcesParams,) => {
    return [`http://localhost:8000/resources/`, ...(params ? [params]: [])] as const;
    }

    
export const getResourcesQueryOptions = <TData = Awaited<ReturnType<typeof resources>>, TError = HTTPValidationError>(params?: ResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResourcesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resources>>> = ({ signal }) => resources(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof resources>>>
export type ResourcesQueryError = HTTPValidationError


export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = HTTPValidationError>(
 params: undefined |  ResourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resources>>,
          TError,
          Awaited<ReturnType<typeof resources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = HTTPValidationError>(
 params?: ResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resources>>,
          TError,
          Awaited<ReturnType<typeof resources>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = HTTPValidationError>(
 params?: ResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Resources
 */

export function useResources<TData = Awaited<ReturnType<typeof resources>>, TError = HTTPValidationError>(
 params?: ResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resources>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResourcesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Upload Resource
 */
export const getUploadResourceUrl = () => {


  

  return `http://localhost:8000/resources/`
}

export const uploadResource = async (bodyUploadResource: BodyUploadResource, options?: RequestInit): Promise<unknown> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadResource.file)

  return customFetch<unknown>(getUploadResourceUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadResource>>, TError,{data: BodyUploadResource}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadResource>>, TError,{data: BodyUploadResource}, TContext> => {

const mutationKey = ['uploadResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadResource>>, {data: BodyUploadResource}> = (props) => {
          const {data} = props ?? {};

          return  uploadResource(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadResourceMutationResult = NonNullable<Awaited<ReturnType<typeof uploadResource>>>
    export type UploadResourceMutationBody = BodyUploadResource
    export type UploadResourceMutationError = HTTPValidationError

    /**
 * @summary Upload Resource
 */
export const useUploadResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadResource>>, TError,{data: BodyUploadResource}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadResource>>,
        TError,
        {data: BodyUploadResource},
        TContext
      > => {

      const mutationOptions = getUploadResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get Resource Meta
 */
export const getGetResourceMetaUrl = () => {


  

  return `http://localhost:8000/resources/meta`
}

export const getResourceMeta = async ( options?: RequestInit): Promise<GetResourceMeta200> => {
  
  return customFetch<GetResourceMeta200>(getGetResourceMetaUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetResourceMetaQueryKey = () => {
    return [`http://localhost:8000/resources/meta`] as const;
    }

    
export const getGetResourceMetaQueryOptions = <TData = Awaited<ReturnType<typeof getResourceMeta>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceMeta>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetResourceMetaQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getResourceMeta>>> = ({ signal }) => getResourceMeta({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getResourceMeta>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetResourceMetaQueryResult = NonNullable<Awaited<ReturnType<typeof getResourceMeta>>>
export type GetResourceMetaQueryError = unknown


export function useGetResourceMeta<TData = Awaited<ReturnType<typeof getResourceMeta>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceMeta>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResourceMeta>>,
          TError,
          Awaited<ReturnType<typeof getResourceMeta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResourceMeta<TData = Awaited<ReturnType<typeof getResourceMeta>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceMeta>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getResourceMeta>>,
          TError,
          Awaited<ReturnType<typeof getResourceMeta>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetResourceMeta<TData = Awaited<ReturnType<typeof getResourceMeta>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceMeta>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Resource Meta
 */

export function useGetResourceMeta<TData = Awaited<ReturnType<typeof getResourceMeta>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getResourceMeta>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetResourceMetaQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Download Output
 */
export const getDownloadOutputResourcesResourceResourceIdDownloadGetUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/resource/${resourceId}/download`
}

export const downloadOutputResourcesResourceResourceIdDownloadGet = async (resourceId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDownloadOutputResourcesResourceResourceIdDownloadGetUrl(resourceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getDownloadOutputResourcesResourceResourceIdDownloadGetQueryKey = (resourceId: string,) => {
    return [`http://localhost:8000/resources/resource/${resourceId}/download`] as const;
    }

    
export const getDownloadOutputResourcesResourceResourceIdDownloadGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadOutputResourcesResourceResourceIdDownloadGetQueryKey(resourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>> = ({ signal }) => downloadOutputResourcesResourceResourceIdDownloadGet(resourceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(resourceId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadOutputResourcesResourceResourceIdDownloadGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>>
export type DownloadOutputResourcesResourceResourceIdDownloadGetQueryError = HTTPValidationError


export function useDownloadOutputResourcesResourceResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadOutputResourcesResourceResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadOutputResourcesResourceResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Output
 */

export function useDownloadOutputResourcesResourceResourceIdDownloadGet<TData = Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadOutputResourcesResourceResourceIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadOutputResourcesResourceResourceIdDownloadGetQueryOptions(resourceId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Resource
 */
export const getResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/resource/${resourceId}`
}

export const resource = async (resourceId: string, options?: RequestInit): Promise<GetResourceResponse> => {
  
  return customFetch<GetResourceResponse>(getResourceUrl(resourceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getResourceQueryKey = (resourceId: string,) => {
    return [`http://localhost:8000/resources/resource/${resourceId}`] as const;
    }

    
export const getResourceQueryOptions = <TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResourceQueryKey(resourceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof resource>>> = ({ signal }) => resource(resourceId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(resourceId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResourceQueryResult = NonNullable<Awaited<ReturnType<typeof resource>>>
export type ResourceQueryError = HTTPValidationError


export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resource>>,
          TError,
          Awaited<ReturnType<typeof resource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resource>>,
          TError,
          Awaited<ReturnType<typeof resource>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Resource
 */

export function useResource<TData = Awaited<ReturnType<typeof resource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resource>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResourceQueryOptions(resourceId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Resource
 */
export const getDeleteResourceUrl = (resourceId: string,) => {


  

  return `http://localhost:8000/resources/resource/${resourceId}`
}

export const deleteResource = async (resourceId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDeleteResourceUrl(resourceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['deleteResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteResource>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  deleteResource(resourceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteResourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteResource>>>
    
    export type DeleteResourceMutationError = HTTPValidationError

    /**
 * @summary Delete Resource
 */
export const useDeleteResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteResource>>,
        TError,
        {resourceId: string},
        TContext
      > => {

      const mutationOptions = getDeleteResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Rename Resource
 */
export const getRenameResourceUrl = (resourceId: string,
    params: RenameResourceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8000/resources/resource/${resourceId}?${stringifiedParams}` : `http://localhost:8000/resources/resource/${resourceId}`
}

export const renameResource = async (resourceId: string,
    params: RenameResourceParams, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getRenameResourceUrl(resourceId,params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRenameResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameResource>>, TError,{resourceId: string;params: RenameResourceParams}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof renameResource>>, TError,{resourceId: string;params: RenameResourceParams}, TContext> => {

const mutationKey = ['renameResource'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameResource>>, {resourceId: string;params: RenameResourceParams}> = (props) => {
          const {resourceId,params} = props ?? {};

          return  renameResource(resourceId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RenameResourceMutationResult = NonNullable<Awaited<ReturnType<typeof renameResource>>>
    
    export type RenameResourceMutationError = HTTPValidationError

    /**
 * @summary Rename Resource
 */
export const useRenameResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameResource>>, TError,{resourceId: string;params: RenameResourceParams}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameResource>>,
        TError,
        {resourceId: string;params: RenameResourceParams},
        TContext
      > => {

      const mutationOptions = getRenameResourceMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    