from ocelescope.ocel.constants.pm4py import OTYPE_COL

EXECUTION_OTYPE_COL = OTYPE_COL
EXECUTION_EID_LIST_COL = "eid_list"
EXECUTION_ACT_LIST_COL = "act_list"
EXECUTION_TSTAMP_LIST_COL = "time_list"
EXECUTION_VARIANT_ID_COL = "variant_id"


VARIANT_OTYPE_COL = OTYPE_COL
VARIANT_ACT_LIST_COL = EXECUTION_ACT_LIST_COL
VARIANT_FREQUENCY_COL = "frequency"
