OTYPE_COL = "ocel:type"
OID_COL = "ocel:oid"
ACTIVITY_COL = "ocel:activity"
EID_COL = "ocel:eid"
TIMESTAMP_COL = "ocel:timestamp"

O2O_SOURCE_ID = "ocel:oid_1"
O2O_TARGET_ID = "ocel:oid_2"
O2O_SOURCE_TYPE = "ocel:type_1"
O2O_TARGET_TYPE = "ocel:type_2"
O2O_QUALIFIER = "ocel:qualifier"

E2O_EVENT_ID = "ocel:eid"
E2O_OBJECT_ID = "ocel:oid"
E2O_OBJECT_TYPE = "ocel:type"
E2O_ACTIVITY = "ocel:activity"
E2O_QUALIFIER = "ocel:qualifier"

OBJECT_CHANGE_CUMCOUNT = "@@cumcount"
OBJECT_CHANGED_FIELD = "ocel:field"

EVENT_DF_COLS = [EID_COL, TIMESTAMP_COL, ACTIVITY_COL]

OBJECT_DF_COLS = [OID_COL, OTYPE_COL]

E2O_DF_COLS = [EID_COL, OID_COL, E2O_QUALIFIER, ACTIVITY_COL, OTYPE_COL]

PM4PY_O2O_DF_COLS = [OID_COL, f"${OID_COL}_2", O2O_QUALIFIER]

O2O_DF_COLS = [O2O_SOURCE_ID, O2O_TARGET_ID, O2O_QUALIFIER]

OBJECT_CHANGES_DF_COLS = [
    OID_COL,
    OTYPE_COL,
    OBJECT_CHANGE_CUMCOUNT,
    TIMESTAMP_COL,
    OBJECT_CHANGED_FIELD,
]
