/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { BodyGetComputedValuesInputOcels } from './bodyGetComputedValuesInputOcels';
import type { BodyGetComputedValuesInputResources } from './bodyGetComputedValuesInputResources';
import type { BodyGetComputedValuesInput } from './bodyGetComputedValuesInput';

export interface BodyGetComputedValues {
  input_ocels: BodyGetComputedValuesInputOcels;
  input_resources: BodyGetComputedValuesInputResources;
  input: BodyGetComputedValuesInput;
}
