/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export interface BodyUploadPlugin {
  /** An OCEL 2.0 event log (.zip format) */
  file: Blob;
}
