/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { DotVisLayoutEngine } from './dotVisLayoutEngine';

export interface DotVis {
  type: 'dot';
  dot_str: string;
  layout_engine: DotVisLayoutEngine;
}
