/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type DotVisLayoutEngine = typeof DotVisLayoutEngine[keyof typeof DotVisLayoutEngine];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DotVisLayoutEngine = {
  circo: 'circo',
  dot: 'dot',
  fdp: 'fdp',
  sfdp: 'sfdp',
  neato: 'neato',
  osage: 'osage',
  patchwork: 'patchwork',
  twopi: 'twopi',
  nop: 'nop',
  nop2: 'nop2',
} as const;
