/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type DownloadOcelOcelsDownloadGetExt = typeof DownloadOcelOcelsDownloadGetExt[keyof typeof DownloadOcelOcelsDownloadGetExt];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DownloadOcelOcelsDownloadGetExt = {
  xmlocel: '.xmlocel',
  jsonocel: '.jsonocel',
  sqlite: '.sqlite',
} as const;
