/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { DownloadOcelOcelsDownloadGetExt } from './downloadOcelOcelsDownloadGetExt';

export type DownloadOcelOcelsDownloadGetParams = {
ext: DownloadOcelOcelsDownloadGetExt;
ocel_id?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};
