/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { E2OCountFilterMode } from './e2OCountFilterMode';
import type { E2OCountFilterRangeItem0 } from './e2OCountFilterRangeItem0';
import type { E2OCountFilterRangeItem1 } from './e2OCountFilterRangeItem1';
import type { E2OCountFilterQualifier } from './e2OCountFilterQualifier';
import type { E2OCountFilterDirection } from './e2OCountFilterDirection';

export interface E2OCountFilter {
  source: string;
  target: string;
  mode?: E2OCountFilterMode;
  /**
   * @minItems 2
   * @maxItems 2
   */
  range: [E2OCountFilterRangeItem0, E2OCountFilterRangeItem1];
  qualifier?: E2OCountFilterQualifier;
  direction?: E2OCountFilterDirection;
}
