/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type E2OCountFilterDirection = typeof E2OCountFilterDirection[keyof typeof E2OCountFilterDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const E2OCountFilterDirection = {
  source: 'source',
  target: 'target',
} as const;
