/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type EventTypeFilterMode = typeof EventTypeFilterMode[keyof typeof EventTypeFilterMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventTypeFilterMode = {
  exclude: 'exclude',
  include: 'include',
} as const;
