/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { EventTypeFilterMode } from './eventTypeFilterMode';

export interface EventTypeFilter {
  event_types: string[];
  mode?: EventTypeFilterMode;
}
