/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { EventAttributeFilterTimeRange } from './eventAttributeFilterTimeRange';
import type { EventAttributeFilterNumberRange } from './eventAttributeFilterNumberRange';
import type { EventAttributeFilterValues } from './eventAttributeFilterValues';
import type { EventAttributeFilterRegex } from './eventAttributeFilterRegex';

export interface EventAttributeFilter {
  target_type: string;
  attribute: string;
  time_range?: EventAttributeFilterTimeRange;
  number_range?: EventAttributeFilterNumberRange;
  values?: EventAttributeFilterValues;
  regex?: EventAttributeFilterRegex;
}
