/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventAttributeFilterNumberRangeAnyOfItem0 } from './eventAttributeFilterNumberRangeAnyOfItem0';
import type { EventAttributeFilterNumberRangeAnyOfItem1 } from './eventAttributeFilterNumberRangeAnyOfItem1';

export type EventAttributeFilterNumberRange = [EventAttributeFilterNumberRangeAnyOfItem0, EventAttributeFilterNumberRangeAnyOfItem1] | null;
