/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type EventIdsParams = {
search?: string | null;
size?: number;
page?: number;
ocel_id?: string | null;
ocel_version?: 'original' | 'filtered' | null;
};
