/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { EventAttributeFilterTimeRangeAnyOfItem0 } from './eventAttributeFilterTimeRangeAnyOfItem0';
import type { EventAttributeFilterTimeRangeAnyOfItem1 } from './eventAttributeFilterTimeRangeAnyOfItem1';

export type EventAttributeFilterTimeRange = [EventAttributeFilterTimeRangeAnyOfItem0, EventAttributeFilterTimeRangeAnyOfItem1] | null;
