/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELExtensionDescription } from './oCELExtensionDescription';

export type GetExtensionMeta200 = {[key: string]: OCELExtensionDescription};
