/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type GetPluginTasksParams = {
plugin_id: string | null;
method_name: string | null;
only_running?: boolean;
};
