/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { Graph } from './graph';
import type { Table } from './table';
import type { SVGVis } from './sVGVis';

export type GetResourceResponseVisualizationAnyOf = Graph | Table | SVGVis;
