/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ResourceInfo } from './resourceInfo';

export type GetResourceMeta200 = {[key: string]: ResourceInfo};
