/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { GraphNodeLabel } from './graphNodeLabel';
import type { GraphNodeShape } from './graphNodeShape';
import type { GraphNodeWidth } from './graphNodeWidth';
import type { GraphNodeHeight } from './graphNodeHeight';
import type { GraphNodeColor } from './graphNodeColor';
import type { GraphNodeX } from './graphNodeX';
import type { GraphNodeY } from './graphNodeY';
import type { GraphNodeBorderColor } from './graphNodeBorderColor';
import type { GraphNodeLabelPos } from './graphNodeLabelPos';

export interface GraphNode {
  id: string;
  label?: GraphNodeLabel;
  shape: GraphNodeShape;
  width?: GraphNodeWidth;
  height?: GraphNodeHeight;
  color?: GraphNodeColor;
  x?: GraphNodeX;
  y?: GraphNodeY;
  border_color?: GraphNodeBorderColor;
  label_pos?: GraphNodeLabelPos;
}
