/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type GraphEdgeArrowsItem1 = 'triangle' | 'circle-triangle' | 'triangle-backcurve' | 'tee' | 'circle' | 'chevron' | 'triangle-tee' | 'triangle-cross' | 'vee' | 'square' | 'diamond' | null;
