/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { GraphvizLayoutConfigEngine } from './graphvizLayoutConfigEngine';
import type { GraphvizLayoutConfigGraphAttrs } from './graphvizLayoutConfigGraphAttrs';
import type { GraphvizLayoutConfigNodeAttrs } from './graphvizLayoutConfigNodeAttrs';
import type { GraphvizLayoutConfigEdgeAttrs } from './graphvizLayoutConfigEdgeAttrs';

export interface GraphvizLayoutConfig {
  engine: GraphvizLayoutConfigEngine;
  graphAttrs: GraphvizLayoutConfigGraphAttrs;
  nodeAttrs: GraphvizLayoutConfigNodeAttrs;
  edgeAttrs: GraphvizLayoutConfigEdgeAttrs;
}
