/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export interface NominalAttribute {
  attribute: string;
  type: 'nominal';
  num_unique: number;
}
