/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { O2OCountFilterMode } from './o2OCountFilterMode';
import type { O2OCountFilterRangeItem0 } from './o2OCountFilterRangeItem0';
import type { O2OCountFilterRangeItem1 } from './o2OCountFilterRangeItem1';
import type { O2OCountFilterQualifier } from './o2OCountFilterQualifier';
import type { O2OCountFilterDirection } from './o2OCountFilterDirection';

export interface O2OCountFilter {
  source: string;
  target: string;
  mode?: O2OCountFilterMode;
  /**
   * @minItems 2
   * @maxItems 2
   */
  range: [O2OCountFilterRangeItem0, O2OCountFilterRangeItem1];
  qualifier?: O2OCountFilterQualifier;
  direction?: O2OCountFilterDirection;
}
