/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type O2OCountFilterDirection = typeof O2OCountFilterDirection[keyof typeof O2OCountFilterDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const O2OCountFilterDirection = {
  source: 'source',
  target: 'target',
} as const;
