/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectAttributeFilterTimeRangeAnyOfItem0 } from './objectAttributeFilterTimeRangeAnyOfItem0';
import type { ObjectAttributeFilterTimeRangeAnyOfItem1 } from './objectAttributeFilterTimeRangeAnyOfItem1';

export type ObjectAttributeFilterTimeRange = [ObjectAttributeFilterTimeRangeAnyOfItem0, ObjectAttributeFilterTimeRangeAnyOfItem1] | null;
