/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */

export type ObjectTypeFilterMode = typeof ObjectTypeFilterMode[keyof typeof ObjectTypeFilterMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectTypeFilterMode = {
  exclude: 'exclude',
  include: 'include',
} as const;
