/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ObjectAttributeFilterTimeRange } from './objectAttributeFilterTimeRange';
import type { ObjectAttributeFilterNumberRange } from './objectAttributeFilterNumberRange';
import type { ObjectAttributeFilterValues } from './objectAttributeFilterValues';
import type { ObjectAttributeFilterRegex } from './objectAttributeFilterRegex';

export interface ObjectAttributeFilter {
  target_type: string;
  attribute: string;
  time_range?: ObjectAttributeFilterTimeRange;
  number_range?: ObjectAttributeFilterNumberRange;
  values?: ObjectAttributeFilterValues;
  regex?: ObjectAttributeFilterRegex;
}
