/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectAttributeFilterNumberRangeAnyOfItem0 } from './objectAttributeFilterNumberRangeAnyOfItem0';
import type { ObjectAttributeFilterNumberRangeAnyOfItem1 } from './objectAttributeFilterNumberRangeAnyOfItem1';

export type ObjectAttributeFilterNumberRange = [ObjectAttributeFilterNumberRangeAnyOfItem0, ObjectAttributeFilterNumberRangeAnyOfItem1] | null;
