/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { ObjectTypeFilter } from './objectTypeFilter';
import type { EventTypeFilter } from './eventTypeFilter';
import type { TimeFrameFilter } from './timeFrameFilter';
import type { O2OCountFilter } from './o2OCountFilter';
import type { E2OCountFilter } from './e2OCountFilter';
import type { EventAttributeFilter } from './eventAttributeFilter';
import type { ObjectAttributeFilter } from './objectAttributeFilter';

export interface OCELFilter {
  object_types?: ObjectTypeFilter;
  event_type?: EventTypeFilter;
  time_range?: TimeFrameFilter;
  o2o_count?: O2OCountFilter[];
  e2o_count?: E2OCountFilter[];
  event_attributes?: EventAttributeFilter[];
  object_attributes?: ObjectAttributeFilter[];
}
