/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELExtensionDescription } from './oCELExtensionDescription';

export interface OcelMetadata {
  id: string;
  name: string;
  created_at: string;
  extensions: OCELExtensionDescription[];
}
