/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELAnnotationDescription } from './oCELAnnotationDescription';
import type { OCELAnnotationExtensionLabel } from './oCELAnnotationExtensionLabel';

export interface OCELAnnotation {
  label: string;
  description?: OCELAnnotationDescription;
  extension_label?: OCELAnnotationExtensionLabel;
}
