/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELResultAnnotation } from './oCELResultAnnotation';

export interface OCELResult {
  type?: 'ocel';
  is_list: boolean;
  annotation: OCELResultAnnotation;
}
