/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OcelListResponseCurrentOcelId } from './ocelListResponseCurrentOcelId';
import type { OcelMetadata } from './ocelMetadata';

export interface OcelListResponse {
  current_ocel_id: OcelListResponseCurrentOcelId;
  ocels: OcelMetadata[];
}
