/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELAnnotationDescription } from './oCELAnnotationDescription';
import type { OCELAnnotationExtension } from './oCELAnnotationExtension';

export interface OCELAnnotation {
  label: string;
  description?: OCELAnnotationDescription;
  extension?: OCELAnnotationExtension;
}
