/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export interface PaginatedResponseListStr {
  response: string[];
  page: number;
  page_size: number;
  total_items: number;
  readonly total_pages: number;
}
