/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ResourceAnnotation } from './resourceAnnotation';

export type PluginMethodInputResources = {[key: string]: [string, ResourceAnnotation]};
