/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { PluginMeta } from './pluginMeta';
import type { PluginMethod } from './pluginMethod';

export interface PluginApi {
  meta: PluginMeta;
  methods: PluginMethod[];
}
