/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { PluginMethodLabel } from './pluginMethodLabel';
import type { PluginMethodDescription } from './pluginMethodDescription';
import type { PluginMethodInputOcels } from './pluginMethodInputOcels';
import type { PluginMethodInputResources } from './pluginMethodInputResources';
import type { PluginMethodResultsItem } from './pluginMethodResultsItem';
import type { PluginMethodInputSchema } from './pluginMethodInputSchema';

export interface PluginMethod {
  name: string;
  label?: PluginMethodLabel;
  description?: PluginMethodDescription;
  input_ocels?: PluginMethodInputOcels;
  input_resources?: PluginMethodInputResources;
  results?: PluginMethodResultsItem[];
  readonly input_schema: PluginMethodInputSchema;
}
