/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELResult } from './oCELResult';
import type { ResourceResult } from './resourceResult';

export type PluginMethodResultsItem = OCELResult | ResourceResult;
