/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { TaskState } from './taskState';
import type { PluginOutput } from './pluginOutput';

export interface PluginTaskSummary {
  id: string;
  state: TaskState;
  plugin_id: string;
  method_name: string;
  output: PluginOutput;
}
