/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { PluginMetaDescription } from './pluginMetaDescription';

export interface PluginMeta {
  name: string;
  version: string;
  label: string;
  description: PluginMetaDescription;
}
