/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export interface PluginSource {
  task_id: string;
  plugin_name: string;
  method_name: string;
  version: string;
}
