/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { OCELAnnotation } from './oCELAnnotation';

export type PluginMethodInputOcels = {[key: string]: OCELAnnotation};
