/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export interface ResourceApi {
  id: string;
  created_at?: string;
  name: string;
  type_label: string;
}
