/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ResourceApiSource } from './resourceApiSource';

export interface ResourceApi {
  type: string;
  created_at?: string;
  name: string;
  source: ResourceApiSource;
  id: string;
}
