/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ResourceResultAnnotation } from './resourceResultAnnotation';

export interface ResourceResult {
  type?: 'resource';
  resource_type: string;
  is_list: boolean;
  annotation: ResourceResultAnnotation;
}
