/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ResourceAnnotationDescription } from './resourceAnnotationDescription';

export interface ResourceAnnotation {
  label: string;
  description?: ResourceAnnotationDescription;
}
