/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { TaskState } from './taskState';
import type { SystemTaskSummaryMetadata } from './systemTaskSummaryMetadata';

export interface SystemTaskSummary {
  id: string;
  state: TaskState;
  name: string;
  metadata: SystemTaskSummaryMetadata;
}
