/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { TableColumnLabel } from './tableColumnLabel';
import type { TableColumnDataType } from './tableColumnDataType';

export interface TableColumn {
  id: string;
  label?: TableColumnLabel;
  data_type?: TableColumnDataType;
  sortable?: boolean;
  visible?: boolean;
}
