/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type TableColumnDataType = typeof TableColumnDataType[keyof typeof TableColumnDataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableColumnDataType = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'date',
  datetime: 'datetime',
} as const;
