/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { TableColumn } from './tableColumn';
import type { TableRowsItem } from './tableRowsItem';

export interface Table {
  type: 'table';
  columns: TableColumn[];
  rows: TableRowsItem[];
}
