/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export type TimeFrameFilterMode = typeof TimeFrameFilterMode[keyof typeof TimeFrameFilterMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeFrameFilterMode = {
  exclude: 'exclude',
  include: 'include',
} as const;
