/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.9.12
 */
import type { TimeFrameFilterTimeRangeItem0 } from './timeFrameFilterTimeRangeItem0';
import type { TimeFrameFilterTimeRangeItem1 } from './timeFrameFilterTimeRangeItem1';
import type { TimeFrameFilterMode } from './timeFrameFilterMode';

export interface TimeFrameFilter {
  /**
   * @minItems 2
   * @maxItems 2
   */
  time_range: [TimeFrameFilterTimeRangeItem0, TimeFrameFilterTimeRangeItem1];
  mode: TimeFrameFilterMode;
}
