/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */

export interface UploadingOcelMetadata {
  name: string;
  task_id: string;
  uploaded_at: string;
}
