/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import type { ValidationErrorLocItem } from './validationErrorLocItem';

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}
