nav:
  - OCEL:
      - ocel/core.md
      - Managers:
          - ocel/managers/objects.md
          - ocel/managers/events.md
          - ocel/managers/e2o.md
          - ocel/managers/o2o.md
      - ocel/extensions.md
      - ocel/filters.md
      - Models:
          - ocel/models/attributes.md
          - ocel/models/relations.md

  - Plugins:
      - plugins/index.md 
