/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OCEL Querying
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../fetcher';
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface NumericBinSchema {
  count?: number | null;
  min?: number | null;
  max?: number | null;
}

export type OcelFieldSchemaType = typeof OcelFieldSchemaType[keyof typeof OcelFieldSchemaType];


export const OcelFieldSchemaType = {
  number: 'number',
  string: 'string',
  boolean: 'boolean',
  datetime: 'datetime',
  unknown: 'unknown',
} as const;

export type OcelFieldSchemaRole = typeof OcelFieldSchemaRole[keyof typeof OcelFieldSchemaRole];


export const OcelFieldSchemaRole = {
  id: 'id',
  type: 'type',
  timestamp: 'timestamp',
  qualifier: 'qualifier',
  attribute: 'attribute',
  technical: 'technical',
} as const;

export type OcelFieldSchemaTypesByEntity = {[key: string]: 'number' | 'string' | 'boolean' | 'datetime' | 'unknown'};

export interface OcelFieldSchema {
  name: string;
  type: OcelFieldSchemaType;
  role: OcelFieldSchemaRole;
  nullable: boolean;
  entity_types: string[];
  types_by_entity: OcelFieldSchemaTypesByEntity;
}

export type OcelQueryBodySource = typeof OcelQueryBodySource[keyof typeof OcelQueryBodySource];


export const OcelQueryBodySource = {
  events: 'events',
  objects: 'objects',
  e2o: 'e2o',
  o2o: 'o2o',
  object_changes: 'object_changes',
} as const;

export type QueryFilterSchemaOperator = typeof QueryFilterSchemaOperator[keyof typeof QueryFilterSchemaOperator];


export const QueryFilterSchemaOperator = {
  eq: 'eq',
  neq: 'neq',
  in: 'in',
  not_in: 'not_in',
  lt: 'lt',
  lte: 'lte',
  gt: 'gt',
  gte: 'gte',
  between: 'between',
  contains: 'contains',
  is_null: 'is_null',
  not_null: 'not_null',
} as const;

export interface QueryFilterSchema {
  field: string;
  operator: QueryFilterSchemaOperator;
  value?: string | number | boolean | (string | number | boolean | null)[] | null;
}

export interface QueryGroupSchema {
  field: string;
  /** @pattern ^[A-Za-z_][A-Za-z0-9_]*$ */
  alias: string;
  bin?: NumericBinSchema | null;
  time_unit?: 'minute' | 'hour' | 'day' | 'week' | 'month' | 'quarter' | 'year' | null;
}

export type QueryMeasureSchemaOperation = typeof QueryMeasureSchemaOperation[keyof typeof QueryMeasureSchemaOperation];


export const QueryMeasureSchemaOperation = {
  count: 'count',
  count_distinct: 'count_distinct',
  sum: 'sum',
  avg: 'avg',
  min: 'min',
  max: 'max',
  median: 'median',
} as const;

export interface QueryMeasureSchema {
  operation: QueryMeasureSchemaOperation;
  /** @pattern ^[A-Za-z_][A-Za-z0-9_]*$ */
  alias: string;
  field?: string | null;
}

export type QueryOrderSchemaDirection = typeof QueryOrderSchemaDirection[keyof typeof QueryOrderSchemaDirection];


export const QueryOrderSchemaDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;

export interface QueryOrderSchema {
  field: string;
  direction?: QueryOrderSchemaDirection;
}

export interface OcelQueryBody {
  source: OcelQueryBodySource;
  /** @maxItems 50 */
  fields?: string[];
  /** @maxItems 20 */
  filters?: QueryFilterSchema[];
  /** @maxItems 3 */
  group_by?: QueryGroupSchema[];
  /** @maxItems 10 */
  measures?: QueryMeasureSchema[];
  /** @maxItems 5 */
  order_by?: QueryOrderSchema[];
  /**
   * @minimum 1
   * @maximum 5000
   */
  limit?: number;
}

export type OcelQueryResponseRowsItem = {[key: string]: string | number | boolean | null};

export type QueryColumnSchemaType = typeof QueryColumnSchemaType[keyof typeof QueryColumnSchemaType];


export const QueryColumnSchemaType = {
  number: 'number',
  string: 'string',
  boolean: 'boolean',
  datetime: 'datetime',
  unknown: 'unknown',
} as const;

export interface QueryColumnSchema {
  name: string;
  type: QueryColumnSchemaType;
}

export interface QueryStatsSchema {
  source_rows: number;
  filtered_rows: number;
  matched_rows: number;
  result_rows: number;
  returned_rows: number;
  truncated: boolean;
}

export interface OcelQueryResponse {
  columns: QueryColumnSchema[];
  rows: OcelQueryResponseRowsItem[];
  stats: QueryStatsSchema;
}

export type OcelSourceSchemaName = typeof OcelSourceSchemaName[keyof typeof OcelSourceSchemaName];


export const OcelSourceSchemaName = {
  events: 'events',
  objects: 'objects',
  e2o: 'e2o',
  o2o: 'o2o',
  object_changes: 'object_changes',
} as const;

export interface OcelSourceSchema {
  name: OcelSourceSchemaName;
  row_count: number;
  fields: OcelFieldSchema[];
  entity_types: string[];
  id_field: string | null;
  type_field: string | null;
  timestamp_field: string | null;
}

export interface OcelSchemaResponse {
  sources: OcelSourceSchema[];
}

export type OcelSchemaParams = {
ocel_version?: 'original' | 'filtered' | null;
};

export type OcelQueryParams = {
ocel_version?: 'original' | 'filtered' | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Ocel Schema
 */
export const ocelSchema = (
    ocelId: string | null,
    params?: OcelSchemaParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<OcelSchemaResponse>(
      {url: `/api/external/modules/querying/v1/${ocelId}/schema`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getOcelSchemaQueryKey = (ocelId: string | null,
    params?: OcelSchemaParams,) => {
    return [
    `/api/external/modules/querying/v1/${ocelId}/schema`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getOcelSchemaQueryOptions = <TData = Awaited<ReturnType<typeof ocelSchema>>, TError = HTTPValidationError>(ocelId: string | null,
    params?: OcelSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOcelSchemaQueryKey(ocelId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ocelSchema>>> = ({ signal }) => ocelSchema(ocelId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ocelSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OcelSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof ocelSchema>>>
export type OcelSchemaQueryError = HTTPValidationError


export function useOcelSchema<TData = Awaited<ReturnType<typeof ocelSchema>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params: undefined |  OcelSchemaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ocelSchema>>,
          TError,
          Awaited<ReturnType<typeof ocelSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOcelSchema<TData = Awaited<ReturnType<typeof ocelSchema>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params?: OcelSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ocelSchema>>,
          TError,
          Awaited<ReturnType<typeof ocelSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOcelSchema<TData = Awaited<ReturnType<typeof ocelSchema>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params?: OcelSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ocel Schema
 */

export function useOcelSchema<TData = Awaited<ReturnType<typeof ocelSchema>>, TError = HTTPValidationError>(
 ocelId: string | null,
    params?: OcelSchemaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelSchema>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOcelSchemaQueryOptions(ocelId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Ocel Query
 */
export const ocelQuery = (
    ocelId: string | null,
    ocelQueryBody: OcelQueryBody,
    params?: OcelQueryParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<OcelQueryResponse>(
      {url: `/api/external/modules/querying/v1/${ocelId}/query`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ocelQueryBody,
        params, signal
    },
      options);
    }
  



export const getOcelQueryQueryKey = (ocelId: string | null,
    ocelQueryBody?: OcelQueryBody,
    params?: OcelQueryParams,) => {
    return [
    `/api/external/modules/querying/v1/${ocelId}/query`, ...(params ? [params] : []), ocelQueryBody
    ] as const;
    }

    
export const getOcelQueryQueryOptions = <TData = Awaited<ReturnType<typeof ocelQuery>>, TError = HTTPValidationError>(ocelId: string | null,
    ocelQueryBody: OcelQueryBody,
    params?: OcelQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelQuery>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOcelQueryQueryKey(ocelId,ocelQueryBody,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ocelQuery>>> = ({ signal }) => ocelQuery(ocelId,ocelQueryBody,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ocelId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ocelQuery>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OcelQueryQueryResult = NonNullable<Awaited<ReturnType<typeof ocelQuery>>>
export type OcelQueryQueryError = HTTPValidationError


export function useOcelQuery<TData = Awaited<ReturnType<typeof ocelQuery>>, TError = HTTPValidationError>(
 ocelId: string | null,
    ocelQueryBody: OcelQueryBody,
    params: undefined |  OcelQueryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelQuery>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ocelQuery>>,
          TError,
          Awaited<ReturnType<typeof ocelQuery>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOcelQuery<TData = Awaited<ReturnType<typeof ocelQuery>>, TError = HTTPValidationError>(
 ocelId: string | null,
    ocelQueryBody: OcelQueryBody,
    params?: OcelQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelQuery>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ocelQuery>>,
          TError,
          Awaited<ReturnType<typeof ocelQuery>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOcelQuery<TData = Awaited<ReturnType<typeof ocelQuery>>, TError = HTTPValidationError>(
 ocelId: string | null,
    ocelQueryBody: OcelQueryBody,
    params?: OcelQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelQuery>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ocel Query
 */

export function useOcelQuery<TData = Awaited<ReturnType<typeof ocelQuery>>, TError = HTTPValidationError>(
 ocelId: string | null,
    ocelQueryBody: OcelQueryBody,
    params?: OcelQueryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ocelQuery>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOcelQueryQueryOptions(ocelId,ocelQueryBody,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
