/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyGetComputedValues,
  BodyRunPlugin,
  BodyUploadPlugin,
  HTTPValidationError,
  PluginApi
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Plugins
 */
export const getPluginsUrl = () => {


  

  return `http://localhost:8000/plugins/`
}

export const plugins = async ( options?: RequestInit): Promise<PluginApi[]> => {
  
  return customFetch<PluginApi[]>(getPluginsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getPluginsQueryKey = () => {
    return [`http://localhost:8000/plugins/`] as const;
    }

    
export const getPluginsQueryOptions = <TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPluginsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof plugins>>> = ({ signal }) => plugins({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PluginsQueryResult = NonNullable<Awaited<ReturnType<typeof plugins>>>
export type PluginsQueryError = unknown


export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof plugins>>,
          TError,
          Awaited<ReturnType<typeof plugins>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof plugins>>,
          TError,
          Awaited<ReturnType<typeof plugins>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Plugins
 */

export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPluginsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Upload Plugin
 */
export const getUploadPluginUrl = () => {


  

  return `http://localhost:8000/plugins/`
}

export const uploadPlugin = async (bodyUploadPlugin: BodyUploadPlugin, options?: RequestInit): Promise<unknown> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadPlugin.file)

  return customFetch<unknown>(getUploadPluginUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadPluginMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPlugin>>, TError,{data: BodyUploadPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadPlugin>>, TError,{data: BodyUploadPlugin}, TContext> => {

const mutationKey = ['uploadPlugin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadPlugin>>, {data: BodyUploadPlugin}> = (props) => {
          const {data} = props ?? {};

          return  uploadPlugin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadPluginMutationResult = NonNullable<Awaited<ReturnType<typeof uploadPlugin>>>
    export type UploadPluginMutationBody = BodyUploadPlugin
    export type UploadPluginMutationError = HTTPValidationError

    /**
 * @summary Upload Plugin
 */
export const useUploadPlugin = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPlugin>>, TError,{data: BodyUploadPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadPlugin>>,
        TError,
        {data: BodyUploadPlugin},
        TContext
      > => {

      const mutationOptions = getUploadPluginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Run Plugin
 */
export const getRunPluginUrl = (pluginName: string,
    methodName: string,) => {


  

  return `http://localhost:8000/plugins/${pluginName}/${methodName}`
}

export const runPlugin = async (pluginName: string,
    methodName: string,
    bodyRunPlugin: BodyRunPlugin, options?: RequestInit): Promise<string> => {
  
  return customFetch<string>(getRunPluginUrl(pluginName,methodName),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyRunPlugin,)
  }
);}




export const getRunPluginMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runPlugin>>, TError,{pluginName: string;methodName: string;data: BodyRunPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runPlugin>>, TError,{pluginName: string;methodName: string;data: BodyRunPlugin}, TContext> => {

const mutationKey = ['runPlugin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runPlugin>>, {pluginName: string;methodName: string;data: BodyRunPlugin}> = (props) => {
          const {pluginName,methodName,data} = props ?? {};

          return  runPlugin(pluginName,methodName,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RunPluginMutationResult = NonNullable<Awaited<ReturnType<typeof runPlugin>>>
    export type RunPluginMutationBody = BodyRunPlugin
    export type RunPluginMutationError = HTTPValidationError

    /**
 * @summary Run Plugin
 */
export const useRunPlugin = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runPlugin>>, TError,{pluginName: string;methodName: string;data: BodyRunPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runPlugin>>,
        TError,
        {pluginName: string;methodName: string;data: BodyRunPlugin},
        TContext
      > => {

      const mutationOptions = getRunPluginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get Computed
 */
export const getGetComputedValuesUrl = (pluginName: string,
    methodName: string,
    provider: string,) => {


  

  return `http://localhost:8000/plugins/${pluginName}/${methodName}/computed/${provider}`
}

export const getComputedValues = async (pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: RequestInit): Promise<string[]> => {
  
  return customFetch<string[]>(getGetComputedValuesUrl(pluginName,methodName,provider),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyGetComputedValues,)
  }
);}



export const getGetComputedValuesQueryKey = (pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues,) => {
    return [`http://localhost:8000/plugins/${pluginName}/${methodName}/computed/${provider}`, bodyGetComputedValues] as const;
    }

    
export const getGetComputedValuesQueryOptions = <TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComputedValuesQueryKey(pluginName,methodName,provider,bodyGetComputedValues);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComputedValues>>> = ({ signal }) => getComputedValues(pluginName,methodName,provider,bodyGetComputedValues, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pluginName && methodName && provider),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComputedValuesQueryResult = NonNullable<Awaited<ReturnType<typeof getComputedValues>>>
export type GetComputedValuesQueryError = HTTPValidationError


export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComputedValues>>,
          TError,
          Awaited<ReturnType<typeof getComputedValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComputedValues>>,
          TError,
          Awaited<ReturnType<typeof getComputedValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Computed
 */

export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginName: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComputedValuesQueryOptions(pluginName,methodName,provider,bodyGetComputedValues,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



