/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OCEAn
 * OpenAPI spec version: 0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyGetComputedValues,
  BodyRunPlugin,
  BodyUploadPlugin,
  GetPlugin200,
  GetPluginMethod200,
  HTTPValidationError,
  PluginApi
} from '../../fastapi-schemas';

import { customFetch } from '../../fetcher';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Plugins
 */
export const getPluginsUrl = () => {


  

  return `http://localhost:8000/plugins/`
}

export const plugins = async ( options?: RequestInit): Promise<PluginApi[]> => {
  
  return customFetch<PluginApi[]>(getPluginsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getPluginsQueryKey = () => {
    return [`http://localhost:8000/plugins/`] as const;
    }

    
export const getPluginsQueryOptions = <TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPluginsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof plugins>>> = ({ signal }) => plugins({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PluginsQueryResult = NonNullable<Awaited<ReturnType<typeof plugins>>>
export type PluginsQueryError = unknown


export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof plugins>>,
          TError,
          Awaited<ReturnType<typeof plugins>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof plugins>>,
          TError,
          Awaited<ReturnType<typeof plugins>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Plugins
 */

export function usePlugins<TData = Awaited<ReturnType<typeof plugins>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof plugins>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPluginsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Upload Plugin
 */
export const getUploadPluginUrl = () => {


  

  return `http://localhost:8000/plugins/`
}

export const uploadPlugin = async (bodyUploadPlugin: BodyUploadPlugin, options?: RequestInit): Promise<unknown> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadPlugin.file)

  return customFetch<unknown>(getUploadPluginUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadPluginMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPlugin>>, TError,{data: BodyUploadPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadPlugin>>, TError,{data: BodyUploadPlugin}, TContext> => {

const mutationKey = ['uploadPlugin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadPlugin>>, {data: BodyUploadPlugin}> = (props) => {
          const {data} = props ?? {};

          return  uploadPlugin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadPluginMutationResult = NonNullable<Awaited<ReturnType<typeof uploadPlugin>>>
    export type UploadPluginMutationBody = BodyUploadPlugin
    export type UploadPluginMutationError = HTTPValidationError

    /**
 * @summary Upload Plugin
 */
export const useUploadPlugin = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadPlugin>>, TError,{data: BodyUploadPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadPlugin>>,
        TError,
        {data: BodyUploadPlugin},
        TContext
      > => {

      const mutationOptions = getUploadPluginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get Plugin
 */
export const getGetPluginUrl = (pluginId: string,) => {


  

  return `http://localhost:8000/plugins/${pluginId}`
}

export const getPlugin = async (pluginId: string, options?: RequestInit): Promise<GetPlugin200> => {
  
  return customFetch<GetPlugin200>(getGetPluginUrl(pluginId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetPluginQueryKey = (pluginId: string,) => {
    return [`http://localhost:8000/plugins/${pluginId}`] as const;
    }

    
export const getGetPluginQueryOptions = <TData = Awaited<ReturnType<typeof getPlugin>>, TError = HTTPValidationError>(pluginId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlugin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPluginQueryKey(pluginId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlugin>>> = ({ signal }) => getPlugin(pluginId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pluginId),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlugin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPluginQueryResult = NonNullable<Awaited<ReturnType<typeof getPlugin>>>
export type GetPluginQueryError = HTTPValidationError


export function useGetPlugin<TData = Awaited<ReturnType<typeof getPlugin>>, TError = HTTPValidationError>(
 pluginId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlugin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlugin>>,
          TError,
          Awaited<ReturnType<typeof getPlugin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlugin<TData = Awaited<ReturnType<typeof getPlugin>>, TError = HTTPValidationError>(
 pluginId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlugin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlugin>>,
          TError,
          Awaited<ReturnType<typeof getPlugin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlugin<TData = Awaited<ReturnType<typeof getPlugin>>, TError = HTTPValidationError>(
 pluginId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlugin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Plugin
 */

export function useGetPlugin<TData = Awaited<ReturnType<typeof getPlugin>>, TError = HTTPValidationError>(
 pluginId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlugin>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPluginQueryOptions(pluginId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete Plugin
 */
export const getDeletePluginUrl = (pluginId: string,) => {


  

  return `http://localhost:8000/plugins/${pluginId}`
}

export const deletePlugin = async (pluginId: string, options?: RequestInit): Promise<unknown> => {
  
  return customFetch<unknown>(getDeletePluginUrl(pluginId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeletePluginMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlugin>>, TError,{pluginId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePlugin>>, TError,{pluginId: string}, TContext> => {

const mutationKey = ['deletePlugin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePlugin>>, {pluginId: string}> = (props) => {
          const {pluginId} = props ?? {};

          return  deletePlugin(pluginId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePluginMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlugin>>>
    
    export type DeletePluginMutationError = HTTPValidationError

    /**
 * @summary Delete Plugin
 */
export const useDeletePlugin = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePlugin>>, TError,{pluginId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePlugin>>,
        TError,
        {pluginId: string},
        TContext
      > => {

      const mutationOptions = getDeletePluginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get Plugin Method
 */
export const getGetPluginMethodUrl = (pluginId: string,
    methodName: string,) => {


  

  return `http://localhost:8000/plugins/${pluginId}/${methodName}`
}

export const getPluginMethod = async (pluginId: string,
    methodName: string, options?: RequestInit): Promise<GetPluginMethod200> => {
  
  return customFetch<GetPluginMethod200>(getGetPluginMethodUrl(pluginId,methodName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export const getGetPluginMethodQueryKey = (pluginId: string,
    methodName: string,) => {
    return [`http://localhost:8000/plugins/${pluginId}/${methodName}`] as const;
    }

    
export const getGetPluginMethodQueryOptions = <TData = Awaited<ReturnType<typeof getPluginMethod>>, TError = HTTPValidationError>(pluginId: string,
    methodName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginMethod>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPluginMethodQueryKey(pluginId,methodName);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPluginMethod>>> = ({ signal }) => getPluginMethod(pluginId,methodName, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pluginId && methodName),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPluginMethod>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPluginMethodQueryResult = NonNullable<Awaited<ReturnType<typeof getPluginMethod>>>
export type GetPluginMethodQueryError = HTTPValidationError


export function useGetPluginMethod<TData = Awaited<ReturnType<typeof getPluginMethod>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginMethod>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPluginMethod>>,
          TError,
          Awaited<ReturnType<typeof getPluginMethod>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPluginMethod<TData = Awaited<ReturnType<typeof getPluginMethod>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginMethod>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPluginMethod>>,
          TError,
          Awaited<ReturnType<typeof getPluginMethod>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPluginMethod<TData = Awaited<ReturnType<typeof getPluginMethod>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginMethod>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Plugin Method
 */

export function useGetPluginMethod<TData = Awaited<ReturnType<typeof getPluginMethod>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPluginMethod>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPluginMethodQueryOptions(pluginId,methodName,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Run Plugin
 */
export const getRunPluginUrl = (pluginId: string,
    methodName: string,) => {


  

  return `http://localhost:8000/plugins/${pluginId}/${methodName}`
}

export const runPlugin = async (pluginId: string,
    methodName: string,
    bodyRunPlugin: BodyRunPlugin, options?: RequestInit): Promise<string> => {
  
  return customFetch<string>(getRunPluginUrl(pluginId,methodName),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyRunPlugin,)
  }
);}




export const getRunPluginMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runPlugin>>, TError,{pluginId: string;methodName: string;data: BodyRunPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof runPlugin>>, TError,{pluginId: string;methodName: string;data: BodyRunPlugin}, TContext> => {

const mutationKey = ['runPlugin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runPlugin>>, {pluginId: string;methodName: string;data: BodyRunPlugin}> = (props) => {
          const {pluginId,methodName,data} = props ?? {};

          return  runPlugin(pluginId,methodName,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RunPluginMutationResult = NonNullable<Awaited<ReturnType<typeof runPlugin>>>
    export type RunPluginMutationBody = BodyRunPlugin
    export type RunPluginMutationError = HTTPValidationError

    /**
 * @summary Run Plugin
 */
export const useRunPlugin = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runPlugin>>, TError,{pluginId: string;methodName: string;data: BodyRunPlugin}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runPlugin>>,
        TError,
        {pluginId: string;methodName: string;data: BodyRunPlugin},
        TContext
      > => {

      const mutationOptions = getRunPluginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Get Computed
 */
export const getGetComputedValuesUrl = (pluginId: string,
    methodName: string,
    provider: string,) => {


  

  return `http://localhost:8000/plugins/${pluginId}/${methodName}/computed/${provider}`
}

export const getComputedValues = async (pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: RequestInit): Promise<string[]> => {
  
  return customFetch<string[]>(getGetComputedValuesUrl(pluginId,methodName,provider),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyGetComputedValues,)
  }
);}



export const getGetComputedValuesQueryKey = (pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues,) => {
    return [`http://localhost:8000/plugins/${pluginId}/${methodName}/computed/${provider}`, bodyGetComputedValues] as const;
    }

    
export const getGetComputedValuesQueryOptions = <TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetComputedValuesQueryKey(pluginId,methodName,provider,bodyGetComputedValues);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getComputedValues>>> = ({ signal }) => getComputedValues(pluginId,methodName,provider,bodyGetComputedValues, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(pluginId && methodName && provider),  staleTime: 300000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetComputedValuesQueryResult = NonNullable<Awaited<ReturnType<typeof getComputedValues>>>
export type GetComputedValuesQueryError = HTTPValidationError


export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComputedValues>>,
          TError,
          Awaited<ReturnType<typeof getComputedValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getComputedValues>>,
          TError,
          Awaited<ReturnType<typeof getComputedValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Computed
 */

export function useGetComputedValues<TData = Awaited<ReturnType<typeof getComputedValues>>, TError = HTTPValidationError>(
 pluginId: string,
    methodName: string,
    provider: string,
    bodyGetComputedValues: BodyGetComputedValues, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getComputedValues>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetComputedValuesQueryOptions(pluginId,methodName,provider,bodyGetComputedValues,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



